{
	programs.nixvim.highlight = {
		CursorLineNr = { fg = "#f1e9d2" ;};
		LineNr = { fg = "#5b5e5a" ;};
		Conceal = { fg = "#838781" ;};
		DiffAdd = { bg = "#40531b"; fg = "NONE" ;};
		DiffChange = { bg = "#2a3a57"; fg = "NONE" ;};
		DiffDelete = { bg = "#893f45"; fg = "NONE" ;};
		DiffText = { bg = "#3a4a67"; fg = "NONE" ;};
		DiffAdded = { fg = "#8fb573" ;};
		DiffRemoved = { fg = "#e75a7c" ;};
		DiffFile = { fg = "#70c2be" ;};
		DiffIndexLine = { fg = "#5b5e5a" ;};
		Directory = { fg = "#57a5e5" ;};
		Operator = { fg = "#C5C2EE" ;};
		Tag = { fg = "#57a5e5" ;};
		Delimiter = { fg = "#838781" ;};
		Comment = { italic = true; fg = "#838781" ;};
		SpecialComment = { link = "Comment" ;};
		Todo = { fg = "#111210"; bold = true; bg = "#aaaaff" ;};
		Underlined = { underline = true ;};
		Bold = { bold = true ;};
		Italic = { italic = true ;};
		Strike = { strikethrough = true ;};
		vimMapLhs = { fg = "#f1e9d2" ;};
		vimMapRhs = { fg = "#57a5e5" ;};
		vimVar = { fg = "#f1e9d2" ;};
		vimCommentTitle = { italic = true; fg = "#dbb651" ;};
		LspDiagnosticsDefaultError = { fg = "#e75a7c" ;};
		LspDiagnosticsDefaultHint = { fg = "#aaaaff" ;};
		LspDiagnosticsDefaultInformation = { fg = "#70c2be" ;};
		LspDiagnosticsDefaultWarning = { fg = "#dbb651" ;};
		LspDiagnosticsUnderlineError = { sp = "#e75a7c"; underline = false; undercurl = true ;};
		LspDiagnosticsUnderlineHint = { sp = "#aaaaff"; underline = false; undercurl = true ;};
		LspDiagnosticsUnderlineInformation = { sp = "#57a5e5"; underline = false; undercurl = true ;};
		LspDiagnosticsUnderlineWarning = { sp = "#dbb651"; underline = false; undercurl = true ;};
		LspDiagnosticsVirtualTextError = { fg = "#e75a7c"; bg = "#382B2C" ;};
		LspDiagnosticsVirtualTextWarning = { fg = "#dbb651"; bg = "#373428" ;};
		LspDiagnosticsVirtualTextInformation = { fg = "#70c2be"; bg = "#2D3633" ;};
		LspDiagnosticsVirtualTextHint = { fg = "#aaaaff"; bg = "#323339" ;};
		AerialTypeParameterIcon = { fg = "#f08080" ;};
		BlinkCmpKindTypeParameter = { reverse = false; fg = "#f08080" ;};
		AerialTextIcon = { fg = "#838781" ;};
		BlinkCmpKindText = { reverse = false; fg = "#838781" ;};
		AerialStructIcon = { fg = "#dbb651" ;};
		BlinkCmpKindStruct = { reverse = false; fg = "#dbb651" ;};
		AerialSnippetIcon = { fg = "#df73ff" ;};
		AerialFileIcon = { fg = "#8fb573" ;};
		AerialReferenceIcon = { fg = "#ff9966" ;};
		BlinkCmpKindReference = { reverse = false; fg = "#ff9966" ;};
		AerialPropertyIcon = { fg = "#70c2be" ;};
		BlinkCmpKindProperty = { reverse = false; fg = "#70c2be" ;};
		AerialPackageIcon = { fg = "#dbb651" ;};
		BlinkCmpKindPackage = { reverse = false; fg = "#dbb651" ;};
		AerialObjectIcon = { fg = "#e75a7c" ;};
		BlinkCmpKindObject = { reverse = false; fg = "#e75a7c" ;};
		AerialNullIcon = { fg = "#5b5e5a" ;};
		BlinkCmpKindNull = { reverse = false; fg = "#5b5e5a" ;};
		AerialNamespaceIcon = { fg = "#96c7ef" ;};
		BlinkCmpKindNamespace = { reverse = false; fg = "#96c7ef" ;};
		AerialNumberIcon = { fg = "#ff9966" ;};
		BlinkCmpKindNumber = { reverse = false; fg = "#ff9966" ;};
		AerialMethodIcon = { fg = "#57a5e5" ;};
		BlinkCmpKindMethod = { reverse = false; fg = "#57a5e5" ;};
		AerialKeyIcon = { fg = "#70c2be" ;};
		BlinkCmpKindKey = { reverse = false; fg = "#70c2be" ;};
		AerialStringIcon = { fg = "#8fb573" ;};
		BlinkCmpKindString = { reverse = false; fg = "#8fb573" ;};
		AerialFolderIcon = { fg = "#96c7ef" ;};
		BlinkCmpKindFolder = { reverse = false; fg = "#96c7ef" ;};
		BlinkCmpKindSnippet = { fg = "#df73ff"; italic = true; reverse = false ;};
		BlinkCmpKindFile = { reverse = false; fg = "#8fb573" ;};
		AerialFieldIcon = { fg = "#70c2be" ;};
		BlinkCmpKindField = { reverse = false; fg = "#70c2be" ;};
		AerialEventIcon = { fg = "#dbb651" ;};
		BlinkCmpKindEvent = { reverse = false; fg = "#dbb651" ;};
		AerialEnumMemberIcon = { fg = "#ff9966" ;};
		BlinkCmpKindEnumMember = { reverse = false; fg = "#ff9966" ;};
		AerialEnumIcon = { fg = "#dbb651" ;};
		BlinkCmpKindEnum = { reverse = false; fg = "#dbb651" ;};
		AerialConstructorIcon = { fg = "#57a5e5" ;};
		BlinkCmpKindConstructor = { reverse = false; fg = "#57a5e5" ;};
		AerialColorIcon = { fg = "#8fb573" ;};
		BlinkCmpKindColor = { reverse = false; fg = "#8fb573" ;};
		AerialClassIcon = { fg = "#dbb651" ;};
		BlinkCmpKindClass = { reverse = false; fg = "#dbb651" ;};
		BlinkCmpKindFunction = { reverse = false; fg = "#57a5e5" ;};
		AerialFunctionIcon = { fg = "#57a5e5" ;};
		BlinkCmpKindOperator = { reverse = false; fg = "#C5C2EE" ;};
		"@attribute" = { fg = "#70c2be" ;};
		"@attribute.typescript" = { fg = "#57a5e5" ;};
		"@boolean" = { link = "Boolean" ;};
		"@character" = { link = "Character" ;};
		"@character.special" = { link = "Special" ;};
		"@comment" = { italic = true; fg = "#e2c792" ;};
		"@comment.error" = { fg = "#111210"; bold = true; bg = "#e75a7c" ;};
		"@comment.note" = { fg = "#111210"; bold = true; bg = "#57a5e5" ;};
		"@comment.todo" = { link = "Todo" ;};
		"@comment.warning" = { fg = "#111210"; bold = true; bg = "#ff9966" ;};
		"@comment.warning.gitcommit" = { bg = "#5C4334" ;};
		"@constant" = { link = "Constant" ;};
		"@constant.builtin" = { link = "Constant" ;};
		"@constant.macro" = { link = "Macro" ;};
		"@constructor" = { bold = true; fg = "#dbb651" ;};
		"@constructor.lua" = { fg = "#dbb651" ;};
		"@diff.delta" = { link = "DiffChange" ;};
		"@diff.minus" = { link = "DiffDelete" ;};
		"@diff.plus" = { link = "DiffAdd" ;};
		"@error" = { link = "Error" ;};
		"@function" = { link = "Function" ;};
		"@function.builtin" = { fg = "#ff9966" ;};
		"@function.call" = { link = "Function" ;};
		"@function.macro" = { fg = "#df73ff" ;};
		"@function.method" = { link = "Function" ;};
		"@function.method.call" = { link = "Function" ;};
		"@keyword" = { link = "Keyword" ;};
		"@keyword.conditional" = { link = "Conditional" ;};
		"@keyword.conditional.ternary" = { link = "Operator" ;};
		"@keyword.coroutine" = { link = "Keyword" ;};
		"@keyword.debug" = { link = "Keyword" ;};
		"@keyword.directive" = { link = "PreProc" ;};
		"@keyword.directive.define" = { bold = true; fg = "#aaaaff" ;};
		"@keyword.exception" = { link = "Exception" ;};
		"@keyword.import" = { link = "Include" ;};
		"@keyword.modifier" = { italic = true; fg = "#aaaaff" ;};
		"@keyword.operator" = { link = "Keyword" ;};
		"@keyword.repeat" = { link = "Repeat" ;};
		"@keyword.return" = { link = "Keyword" ;};
		"@keyword.type" = { link = "Keyword" ;};
		"@label" = { link = "Label" ;};
		"@label.diff" = { fg = "#dbb651" ;};
		"@markup.heading" = { link = "htmlTitle" ;};
		htmlTitle = { bold = true; fg = "#ff9966" ;};
		"@markup.heading.1" = { link = "markdownH1" ;};
		markdownH1 = { link = "htmlH1" ;};
		"@markup.heading.2" = { link = "markdownH2" ;};
		markdownH2 = { link = "htmlH2" ;};
		"@markup.heading.3" = { link = "markdownH3" ;};
		markdownH3 = { link = "htmlH3" ;};
		"@markup.heading.4" = { link = "markdownH4" ;};
		markdownH4 = { link = "htmlH4" ;};
		"@markup.heading.5" = { link = "markdownH5" ;};
		markdownH5 = { link = "htmlH5" ;};
		"@markup.heading.6" = { link = "markdownH6" ;};
		markdownH6 = { link = "htmlH6" ;};
		"@markup.italic" = { link = "markdownItalic" ;};
		markdownItalic = { link = "htmlItalic" ;};
		"@markup.link" = { link = "Tag" ;};
		"@markup.link.label" = { link = "markdownLinkText" ;};
		markdownLinkText = { link = "htmlLink" ;};
		"@markup.link.url" = { link = "markdownUrl" ;};
		markdownUrl = { underline = true; fg = "#70c2be"; italic = true ;};
		"@markup.list" = { link = "markdownListMarker" ;};
		markdownListMarker = { link = "Special" ;};
		"@markup.list.checked" = { bold = true; fg = "#dbb651" ;};
		"@markup.list.unchecked" = { bold = true; fg = "#838781" ;};
		"@markup.math" = { fg = "#96c7ef" ;};
		"@markup.quote" = { fg = "#838781" ;};
		"@markup.raw" = { link = "markdownCode" ;};
		markdownCode = { fg = "#8fb573" ;};
		"@markup.raw.block" = { link = "markdownCodeBlock" ;};
		markdownCodeBlock = { link = "markdownCode" ;};
		"@markup.strikethrough" = { link = "markdownStrike" ;};
		markdownStrike = { link = "htmlStrike" ;};
		"@markup.strong" = { link = "markdownBold" ;};
		markdownBold = { link = "htmlBold" ;};
		"@markup.underline" = { link = "htmlUnderline" ;};
		htmlUnderline = { underline = true; fg = "#ff9966" ;};
		"@module" = { italic = true; fg = "#96c7ef" ;};
		"@module.builtin" = { link = "@variable.builtin" ;};
		"@variable.builtin" = { fg = "#e75a7c" ;};
		"@module.latex" = { italic = true; fg = "#70c2be" ;};
		"@number" = { link = "Number" ;};
		"@number.float" = { link = "Float" ;};
		"@operator" = { link = "Operator" ;};
		"@property" = { link = "@variable.member" ;};
		"@variable.member" = { fg = "#70c2be" ;};
		"@punctuation.bracket" = { link = "Delimiter" ;};
		"@punctuation.delimiter" = { link = "Delimiter" ;};
		"@punctuation.special" = { link = "Special" ;};
		"@punctuation.special.diff" = { link = "Delimiter" ;};
		"@string" = { link = "String" ;};
		"@string.documentation" = { fg = "#ABC896" ;};
		AerialArrayIcon = { fg = "#dbb651" ;};
		BlinkCmpKindArray = { reverse = false; fg = "#dbb651" ;};
		AerialDefaultIcon = { fg = "#aaaaff" ;};
		BlinkCmpKindDefault = { reverse = false; fg = "#aaaaff" ;};
		AerialBooleanIcon = { fg = "#ff9966" ;};
		BlinkCmpKindBoolean = { reverse = false; fg = "#ff9966" ;};
		AerialModuleIcon = { fg = "#96c7ef" ;};
		BlinkCmpKindModule = { reverse = false; fg = "#96c7ef" ;};
		AerialConstantIcon = { fg = "#ff9966" ;};
		BlinkCmpKindConstant = { reverse = false; fg = "#ff9966" ;};
		AerialInterfaceIcon = { fg = "#8fb573" ;};
		BlinkCmpKindInterface = { reverse = false; fg = "#8fb573" ;};
		AerialValueIcon = { fg = "#ff9966" ;};
		BlinkCmpKindValue = { reverse = false; fg = "#ff9966" ;};
		AerialOperatorIcon = { fg = "#C5C2EE" ;};
		AerialVariableIcon = { fg = "#e75a7c" ;};
		BlinkCmpKindVariable = { reverse = false; fg = "#e75a7c" ;};
		AerialKeywordIcon = { fg = "#aaaaff" ;};
		BlinkCmpKindKeyword = { reverse = false; fg = "#aaaaff" ;};
		AerialUnitIcon = { fg = "#dbb651" ;};
		BlinkCmpKindUnit = { reverse = false; fg = "#dbb651" ;};
		vimNotation = { fg = "#e75a7c" ;};
		vimMapModKey = { fg = "#ff9966" ;};
		vimMap = { fg = "#aaaaff" ;};
		vimSetEqual = { fg = "#dbb651" ;};
		vimOption = { fg = "#e75a7c" ;};
		texPgfType = { fg = "#dbb651" ;};
		texCmdPackage = { fg = "#57a5e5" ;};
		texCmdPart = { fg = "#57a5e5" ;};
		texCmd = { fg = "#aaaaff" ;};
		texMathOper = { fg = "#e75a7c" ;};
		"@string.escape" = { fg = "#f08080" ;};
		"@string.regexp" = { link = "Constant" ;};
		"@string.special" = { link = "Special" ;};
		"@string.special.path" = { underline = true; fg = "#96c7ef" ;};
		"@string.special.path.diff" = { fg = "#96c7ef" ;};
		"@string.special.symbol" = { link = "@variable.member" ;};
		"@string.special.url" = { underline = true; fg = "#70c2be"; italic = true ;};
		"@tag" = { fg = "#aaaaff" ;};
		"@tag.attribute" = { link = "@variable.member" ;};
		"@tag.builtin" = { link = "@tag" ;};
		"@tag.delimiter" = { link = "Delimiter" ;};
		"@type" = { link = "Type" ;};
		"@type.builtin" = { link = "Type" ;};
		"@type.definition" = { link = "Type" ;};
		"@variable" = { fg = "#f1e9d2" ;};
		"@variable.parameter" = { italic = true; fg = "#f08080" ;};
		"@variable.parameter.builtin" = { italic = true; fg = "#e75a7c" ;};
		"@lsp.mod.readonly" = { link = "@constant" ;};
		"@lsp.mod.typeHint" = { link = "@type" ;};
		"@lsp.type.boolean" = { link = "@boolean" ;};
		"@lsp.type.builtinAttribute" = { link = "@attribute" ;};
		"@lsp.type.builtinConstant" = { link = "@constant.builtin" ;};
		"@lsp.type.builtinType" = { link = "@type.builtin" ;};
		"@lsp.type.class.markdown" = { };
		"@lsp.type.comment" = { };
		"@lsp.type.decorator" = { link = "@attribute" ;};
		"@lsp.type.derive" = { link = "@constructor" ;};
		"@lsp.type.deriveHelper" = { link = "@attribute" ;};
		"@lsp.type.enum" = { link = "@type" ;};
		texMathDelim = { fg = "#aaaaff" ;};
		texMathDelimZone = { fg = "#838781" ;};
		texMathZoneXX = { fg = "#ff9966" ;};
		texMathZoneX = { fg = "#ff9966" ;};
		texEnvArgName = { fg = "#dbb651" ;};
		WarningMsg = { bold = true; fg = "#dbb651" ;};
		texCmdEnv = { fg = "#70c2be" ;};
		markdownUrlTitleDelimiter = { link = "String" ;};
		markdownUrlDelimiter = { link = "Delimiter" ;};
		markdownStrikeDelimiter = { link = "Delimiter" ;};
		markdownRule = { link = "Special" ;};
		markdownOrderedListMarker = { link = "markdownListMarker" ;};
		markdownLinkTextDelimiter = { link = "Delimiter" ;};
		markdownLinkDelimiter = { link = "Delimiter" ;};
		markdownItalicDelimiter = { italic = true; fg = "#838781" ;};
		markdownIdDeclaration = { link = "markdownLinkText" ;};
		markdownId = { link = "markdownLinkText" ;};
		markdownHeadingRule = { link = "markdownHeadingDelimiter" ;};
		markdownH6Delimiter = { link = "markdownH6" ;};
		markdownH5Delimiter = { link = "markdownH5" ;};
		markdownH4Delimiter = { link = "markdownH4" ;};
		markdownH3Delimiter = { link = "markdownH3" ;};
		markdownH2Delimiter = { link = "markdownH2" ;};
		markdownH1Delimiter = { link = "markdownH1" ;};
		markdownHeadingDelimiter = { link = "htmlTitle" ;};
		markdownFootnoteDefinition = { link = "markdownLinkText" ;};
		markdownFootnote = { link = "markdownLinkText" ;};
		markdownCodeDelimiter = { link = "Delimiter" ;};
		markdownBoldDelimiter = { bold = true; fg = "#838781" ;};
		markdownBlockquote = { link = "Special" ;};
		htmlBoldUnderlineItalic = { underline = true; fg = "#ff9966"; bold = true; italic = true ;};
		htmlUnderlineItalic = { fg = "#ff9966"; underline = true; italic = true ;};
		htmlBoldUnderline = { fg = "#ff9966"; bold = true; underline = true ;};
		htmlBoldItalic = { fg = "#ff9966"; bold = true; italic = true ;};
		htmlEndTag = { link = "Delimiter" ;};
		htmlTag = { link = "Delimiter" ;};
		htmlLink = { underline = true; fg = "#57a5e5" ;};
		htmlStrike = { strikethrough = true; fg = "#ff9966" ;};
		htmlItalic = { italic = true; fg = "#ff9966" ;};
		htmlBold = { bold = true; fg = "#ff9966" ;};
		htmlH6 = { bold = true; fg = "#81BCEC" ;};
		htmlH5 = { bold = true; fg = "#94D1CE" ;};
		htmlH4 = { bold = true; fg = "#ABC896" ;};
		htmlH3 = { bold = true; fg = "#E4C87D" ;};
		htmlH2 = { bold = true; fg = "#FFB38C" ;};
		htmlH1 = { bold = true; fg = "#ED839D" ;};
		escCsvCol8 = { link = "csvCol8" ;};
		escCsvCol7 = { link = "csvCol7" ;};
		escCsvCol6 = { link = "csvCol6" ;};
		escCsvCol5 = { link = "csvCol5" ;};
		escCsvCol4 = { link = "csvCol4" ;};
		escCsvCol3 = { link = "csvCol3" ;};
		escCsvCol2 = { link = "csvCol2" ;};
		escCsvCol1 = { link = "csvCol1" ;};
		escCsvCol0 = { link = "csvCol0" ;};
		csvCol8 = { fg = "#f1e9d2" ;};
		csvCol7 = { fg = "#df73ff" ;};
		csvCol6 = { fg = "#aaaaff" ;};
		csvCol5 = { fg = "#57a5e5" ;};
		csvCol4 = { fg = "#70c2be" ;};
		csvCol3 = { fg = "#8fb573" ;};
		csvCol2 = { fg = "#dbb651" ;};
		csvCol1 = { fg = "#ff9966" ;};
		csvCol0 = { fg = "#e75a7c" ;};
		cppStatement = { bold = true; fg = "#aaaaff" ;};
		cDefine = { fg = "#70c2be" ;};
		CurSearch = { bg = "#ff9966"; fg = "#252623" ;};
		IncSearch = { link = "CurSearch" ;};
		Search = { bg = "#e2c792"; fg = "#252623" ;};
		Substitute = { bg = "#8fb573"; fg = "#252623" ;};
		MatchParen = { fg = "#ff9966"; bold = true; bg = "#5b5e5a" ;};
		ModeMsg = { bold = true; fg = "#94D1CE" ;};
		NonText = { fg = "#5b5e5a" ;};
		Whitespace = { link = "NonText" ;};
		SpecialKey = { link = "NonText" ;};
		Pmenu = { bg = "#2f312c"; fg = "#f1e9d2" ;};
		PmenuSbar = { bg = "#2f312c"; fg = "NONE" ;};
		PmenuSel = { bg = "#3a3d37" ;};
		WildMenu = { bg = "#57a5e5"; fg = "#252623" ;};
		PmenuThumb = { bg = "#5b5e5a"; fg = "NONE" ;};
		Question = { fg = "#dbb651" ;};
		SpellBad = { sp = "#e75a7c"; undercurl = true; fg = "NONE" ;};
		SpellCap = { sp = "#dbb651"; undercurl = true; fg = "NONE" ;};
		SpellLocal = { sp = "#57a5e5"; undercurl = true; fg = "NONE" ;};
		SpellRare = { sp = "#aaaaff"; undercurl = true; fg = "NONE" ;};
		StatusLine = { bg = "#383b35"; fg = "#f1e9d2" ;};
		StatusLineNC = { bg = "#2f312c"; fg = "#5b5e5a" ;};
		TabLine = { bg = "#2f312c"; fg = "#f1e9d2" ;};
		TabLineFill = { bg = "#2f312c"; fg = "#5b5e5a" ;};
		TabLineSel = { bg = "#f1e9d2"; fg = "#252623" ;};
		VertSplit = { fg = "#3a3d37" ;};
		Title = { bold = true; fg = "#70c2be" ;};
		Visual = { bg = "#3a3d37" ;};
		VisualNOS = { fg = "NONE"; underline = true; bg = "#383b35" ;};
		WinSeparator = { fg = "#3a3d37" ;};
		WinBar = { fg = "#838781" ;};
		WinBarNC = { link = "WinBar" ;};
		QuickFixLine = { underline = true; fg = "#57a5e5" ;};
		Debug = { fg = "#ff9966" ;};
		debugPC = { bg = "#1c1e1b" ;};
		debugBreakpoint = { bg = "#e75a7c"; fg = "#252623" ;};
		ToolbarButton = { bg = "#68aee8"; fg = "#252623" ;};
		String = { fg = "#8fb573" ;};
		Constant = { fg = "#ff9966" ;};
		Character = { link = "Constant" ;};
		Number = { link = "Constant" ;};
		Float = { link = "Constant" ;};
		Boolean = { link = "Constant" ;};
		Type = { fg = "#dbb651" ;};
		Structure = { link = "Type" ;};
		Statement = { fg = "#aaaaff" ;};
		Identifier = { fg = "#e75a7c" ;};
		PreCondit = { link = "PreProc" ;};
		LspInlayHint = { fg = "#5b5e5a" ;};
		LspCodeLensSeparator = { fg = "#5b5e5a" ;};
		LspCodeLens = { link = "Comment" ;};
		LspReferenceRead = { bg = "#383b35" ;};
		LspReferenceWrite = { bg = "#383b35" ;};
		LspReferenceText = { bg = "#383b35" ;};
		DiagnosticUnderlineOk = { sp = "#8fb573"; underline = false; undercurl = true ;};
		DiagnosticUnderlineWarn = { sp = "#dbb651"; underline = false; undercurl = true ;};
		DiagnosticUnderlineInfo = { sp = "#57a5e5"; underline = false; undercurl = true ;};
		DiagnosticUnderlineHint = { sp = "#aaaaff"; underline = false; undercurl = true ;};
		DiagnosticUnderlineError = { sp = "#e75a7c"; underline = false; undercurl = true ;};
		DiagnosticVirtualTextHint = { fg = "#aaaaff"; bg = "#323339" ;};
		DiagnosticVirtualTextInfo = { fg = "#70c2be"; bg = "#2D3633" ;};
		DiagnosticVirtualTextWarn = { fg = "#dbb651"; bg = "#373428" ;};
		DiagnosticVirtualTextError = { fg = "#e75a7c"; bg = "#382B2C" ;};
		DiagnosticWarn = { fg = "#dbb651" ;};
		DiagnosticInfo = { fg = "#70c2be" ;};
		DiagnosticHint = { fg = "#aaaaff" ;};
		DiagnosticError = { fg = "#e75a7c" ;};
		DiagnosticUnnecessary = { link = "Comment" ;};
		DiagnosticOk = { fg = "#8fb573" ;};
		DiagnosticDeprecated = { link = "Strike" ;};
		TreesitterContext = { bg = "#2f312c" ;};
		"@lsp.typemod.variable.static" = { fg = "#96c7ef" ;};
		"@lsp.typemod.variable.mutable" = { fg = "#CCD6AE" ;};
		"@lsp.typemod.variable.injected" = { link = "@variable" ;};
		"@lsp.typemod.variable.global" = { fg = "#F098AD" ;};
		"@lsp.typemod.variable.defaultLibrary" = { link = "@variable.builtin" ;};
		"@lsp.typemod.variable.callable" = { link = "@function" ;};
		Include = { link = "PreProc" ;};
		BlinkCmpGhostText = { nocombine = true; fg = "#838781"; italic = true; bg = "#252623" ;};
		PreProc = { fg = "#aaaaff" ;};
		BlinkCmpLabel = { fg = "#f1e9d2" ;};
		BlinkCmpLabelMatch = { fg = "#70c2be" ;};
		BlinkCmpLabelDeprecated = { strikethrough = true; fg = "#838781" ;};
		BlinkCmpKind = { reverse = false; fg = "#aaaaff" ;};
		BlinkCmpKindCopilot = { reverse = false; fg = "#70c2be" ;};
		BlinkCmpMenu = { link = "NormalFloat" ;};
		BlinkCmpMenuBorder = { link = "FloatBorder" ;};
		BlinkCmpDocBorder = { link = "FloatBorder" ;};
		DropBarMenuNormalFloat = { link = "Pmenu" ;};
		DropBarMenuCurrentContext = { bold = true; fg = "#FFB38C" ;};
		GitSignsAdd = { fg = "#8fb573" ;};
		GitSignsAddLn = { fg = "#8fb573" ;};
		GitSignsAddNr = { fg = "#8fb573" ;};
		GitSignsChange = { fg = "#57a5e5" ;};
		GitSignsChangeLn = { fg = "#57a5e5" ;};
		GitSignsChangeNr = { fg = "#57a5e5" ;};
		GitSignsDelete = { fg = "#e75a7c" ;};
		GitSignsDeleteLn = { fg = "#e75a7c" ;};
		GitSignsDeleteNr = { fg = "#e75a7c" ;};
		GitSignsUntracked = { fg = "#dbb651" ;};
		GitSignsUntrackedLn = { fg = "#dbb651" ;};
		GitSignsUntrackedNr = { fg = "#dbb651" ;};
		AerialLine = { fg = "#aaaaff"; bold = true; bg = "#383b35" ;};
		RainbowDelimiterRed = { fg = "#ED839D" ;};
		RainbowDelimiterYellow = { fg = "#E4C87D" ;};
		RainbowDelimiterBlue = { fg = "#81BCEC" ;};
		RainbowDelimiterOrange = { fg = "#FFB38C" ;};
		RainbowDelimiterGreen = { fg = "#ABC896" ;};
		RainbowDelimiterViolet = { fg = "#BFBFFF" ;};
		RainbowDelimiterCyan = { fg = "#94D1CE" ;};
		MiniHipatternsFixme = { fg = "#252623"; bold = true; bg = "#e75a7c" ;};
		MiniHipatternsHack = { fg = "#252623"; bold = true; bg = "#dbb651" ;};
		MiniHipatternsNote = { fg = "#252623"; bold = true; bg = "#70c2be" ;};
		MiniHipatternsTodo = { fg = "#252623"; bold = true; bg = "#aaaaff" ;};
		MiniIconsAzure = { fg = "#68aee8" ;};
		MiniIconsBlue = { fg = "#57a5e5" ;};
		MiniIconsCyan = { fg = "#70c2be" ;};
		MiniIconsGreen = { fg = "#8fb573" ;};
		MiniIconsGrey = { fg = "#838781" ;};
		MiniIconsOrange = { fg = "#ff9966" ;};
		MiniIconsPurple = { fg = "#aaaaff" ;};
		MiniIconsRed = { fg = "#e75a7c" ;};
		MiniIconsYellow = { fg = "#dbb651" ;};
		cInclude = { fg = "#57a5e5" ;};
		cStorageClass = { fg = "#aaaaff" ;};
		cTypedef = { fg = "#aaaaff" ;};
		MoreMsg = { bold = true; fg = "#57a5e5" ;};
		Label = { bold = true; fg = "#e75a7c" ;};
		ErrorMsg = { bold = true; fg = "#e75a7c" ;};
		Special = { fg = "#e75a7c" ;};
		SpecialChar = { link = "Special" ;};
		Function = { fg = "#57a5e5" ;};
		Define = { link = "PreProc" ;};
		Keyword = { fg = "#aaaaff" ;};
		Exception = { link = "Keyword" ;};
		Repeat = { link = "Keyword" ;};
		Typedef = { link = "Type" ;};
		Macro = { fg = "#df73ff" ;};
		Normal = { bg = "#252623"; fg = "#f1e9d2" ;};
		NormalNC = { bg = "#252623"; fg = "#f1e9d2" ;};
		NormalFloat = { bg = "#252623"; fg = "#f1e9d2" ;};
		FloatBorder = { bg = "#252623"; fg = "#aaaaff" ;};
		FloatTitle = { fg = "#e75a7c" ;};
		FloatFooter = { fg = "#838781" ;};
		Terminal = { bg = "#252623"; fg = "#f1e9d2" ;};
		EndOfBuffer = { fg = "#252623" ;};
		Conditional = { italic = true; fg = "#aaaaff" ;};
		Error = { fg = "#e75a7c" ;};
		"@lsp.type.enumMember" = { link = "@constant" ;};
		"@lsp.type.escapeSequence" = { link = "@string.escape" ;};
		"@lsp.type.event" = { link = "Label" ;};
		"@lsp.type.formatSpecifier" = { link = "@punctuation.special" ;};
		"@lsp.type.generic" = { };
		"@lsp.type.interface" = { link = "@type" ;};
		"@lsp.type.keyword" = { link = "@keyword" ;};
		"@lsp.type.lifetime" = { link = "StorageClass" ;};
		"@lsp.type.macro" = { link = "Macro" ;};
		"@lsp.type.magicFunction" = { link = "@function.builtin" ;};
		"@lsp.type.method" = { link = "@function.method" ;};
		"@lsp.type.namespace" = { link = "@module" ;};
		"@lsp.type.number" = { link = "@number" ;};
		"@lsp.type.operator" = { link = "@operator" ;};
		"@lsp.type.operator.cpp" = { };
		"@lsp.type.parameter" = { link = "@variable.parameter" ;};
		"@lsp.type.property" = { link = "@property" ;};
		"@lsp.type.selfKeyword" = { link = "@variable.builtin" ;};
		"@lsp.type.selfTypeKeyword" = { link = "@type" ;};
		"@lsp.type.string" = { link = "" ;};
		"@lsp.type.typeAlias" = { link = "@type.definition" ;};
		"@lsp.type.typeParameter" = { link = "@type" ;};
		"@lsp.type.unresolvedReference" = { sp = "#e75a7c"; undercurl = true ;};
		"@lsp.type.variable" = { };
		"@lsp.typemod.class.defaultLibrary" = { link = "@type.builtin" ;};
		"@lsp.typemod.enum.defaultLibrary" = { link = "@type.builtin" ;};
		"@lsp.typemod.enumMember.defaultLibrary" = { link = "@constant.builtin" ;};
		"@lsp.typemod.function.defaultLibrary" = { link = "@function.builtin" ;};
		"@lsp.typemod.function.builtin" = { link = "@function.builtin" ;};
		"@lsp.typemod.function.readonly" = { link = "@function.method" ;};
		"@lsp.typemod.generic.attribute" = { link = "@keyword" ;};
		"@lsp.typemod.keyword.async" = { link = "@keyword.coroutine" ;};
		"@lsp.typemod.keyword.injected" = { link = "@keyword" ;};
		"@lsp.typemod.macro.defaultLibrary" = { link = "@function.builtin" ;};
		"@lsp.typemod.method.defaultLibrary" = { link = "@function.builtin" ;};
		"@lsp.typemod.method.readonly" = { link = "@function.method" ;};
		"@lsp.typemod.operator.injected" = { link = "@operator" ;};
		"@lsp.typemod.parameter.mutable" = { fg = "#E28899" ;};
		"@lsp.typemod.parameter.readonly" = { fg = "#F88D73" ;};
		"@lsp.typemod.property.readonly" = { fg = "#80BC99" ;};
		"@lsp.typemod.string.injected" = { link = "@string" ;};
		"@lsp.typemod.struct.defaultLibrary" = { link = "@type.builtin" ;};
		"@lsp.typemod.type.defaultLibrary" = { link = "@type.builtin" ;};
		"@lsp.typemod.typeAlias.defaultLibrary" = { link = "@type.builtin" ;};
		FoldColumn = { fg = "#f1e9d2" ;};
		Folded = { bg = "#2f312c"; fg = "#f1e9d2" ;};
		SignColumn = { fg = "#f1e9d2" ;};
		ToolbarLine = { fg = "#f1e9d2" ;};
		Cursor = { reverse = true ;};
		lCursor = { link = "Cursor" ;};
		StorageClass = { italic = true; fg = "#dbb651" ;};
		CursorIM = { link = "Cursor" ;};
		CursorColumn = { link = "CursorLine" ;};
		CursorLine = { bg = "#2f312c" ;};
		ColorColumn = { bg = "#3B4235" ;};
	};

	programs.nixvim.globals = {
		terminal_color_7 = "#f1e9d2";
		terminal_color_8 = "#5b5e5a";
		terminal_color_9 = "#e75a7c";
		terminal_color_10 = "#8fb573";
		terminal_color_11 = "#dbb651";
		terminal_color_12 = "#57a5e5";
		terminal_color_13 = "#aaaaff";
		terminal_color_14 = "#70c2be";
		terminal_color_15 = "#f1e9d2";
		terminal_color_0 = "#111210";
		terminal_color_1 = "#e75a7c";
		terminal_color_2 = "#8fb573";
		terminal_color_3 = "#dbb651";
		terminal_color_4 = "#57a5e5";
		terminal_color_5 = "#aaaaff";
		terminal_color_6 = "#70c2be";
	};
}