{
	programs.nixvim.highlight = {
		"@string.special.path.gitignore" = { fg = "#ebdbb2" ;};
		"@comment.warning.gitcommit" = { fg = "#d8a657" ;};
		"@type.builtin.cpp" = { fg = "#d8a657" ;};
		"@property.cpp" = { fg = "#ebdbb2" ;};
		"@type.builtin.c" = { fg = "#d8a657" ;};
		"@variable.member.yaml" = { fg = "#83a598" ;};
		"@constructor.lua" = { fg = "#eb7a73" ;};
		"@label.json" = { fg = "#83a598" ;};
		"@property.toml" = { fg = "#83a598" ;};
		"@markup.heading.6.markdown" = { link = "rainbow6" ;};
		"@markup.heading.5.markdown" = { link = "rainbow5" ;};
		"@markup.heading.4.markdown" = { link = "rainbow4" ;};
		"@markup.heading.3.markdown" = { link = "rainbow3" ;};
		"@markup.heading.2.markdown" = { link = "rainbow2" ;};
		"@markup.heading.1.markdown" = { link = "rainbow1" ;};
		"@function.builtin.bash" = { italic = true; fg = "#ea6962" ;};
		"@error" = { link = "Error" ;};
		"@tag.delimiter" = { fg = "#99c792" ;};
		"@tag.attribute" = { italic = true; fg = "#8ec07c" ;};
		"@tag" = { fg = "#e396a4" ;};
		"@diff.delta" = { link = "diffChanged" ;};
		"@diff.minus" = { link = "diffRemoved" ;};
		"@diff.plus" = { link = "diffAdded" ;};
		"@markup.list.unchecked" = { fg = "#928374" ;};
		"@markup.list.checked" = { fg = "#a9b665" ;};
		"@markup.list" = { link = "Special" ;};
		"@markup.raw" = { fg = "#8ec07c" ;};
		"@markup.link.url" = { italic = true; underline = true; fg = "#eb7a73" ;};
		"@markup.link.label" = { link = "Label" ;};
		"@markup.link" = { link = "Tag" ;};
		"@markup.environment.name" = { fg = "#83a598" ;};
		"@markup.environment" = { fg = "#d3869b" ;};
		"@markup.quote" = { bold = true; fg = "#ea6962" ;};
		"@markup.math" = { fg = "#83a598" ;};
		"@markup.heading" = { bold = true; fg = "#83a598" ;};
		"@markup.underline" = { link = "Underlined" ;};
		"@markup.strikethrough" = { strikethrough = true; fg = "#ebdbb2" ;};
		"@markup.italic" = { italic = true; fg = "#ea6962" ;};
		"@markup.strong" = { bold = true; fg = "#ea6962" ;};
		"@markup" = { fg = "#ebdbb2" ;};
		"@comment.note" = { bg = "#eb7a73"; fg = "#1d2021" ;};
		"@lsp.type.boolean" = { link = "@boolean" ;};
		"@lsp.type.builtinType" = { link = "@type.builtin" ;};
		"@comment.warning" = { bg = "#d8a657"; fg = "#1d2021" ;};
		"@lsp.type.comment" = { link = "@comment" ;};
		"@comment.documentation" = { link = "Comment" ;};
		"@comment" = { link = "Comment" ;};
		"@punctuation.special" = { link = "Special" ;};
		"@punctuation.bracket" = { fg = "#a89984" ;};
		"@punctuation.delimiter" = { link = "Delimiter" ;};
		"@keyword.export" = { fg = "#99c792" ;};
		"@keyword.directive.define" = { link = "Define" ;};
		"@keyword.directive" = { link = "PreProc" ;};
		"@keyword.conditional.ternary" = { link = "Operator" ;};
		"@keyword.conditional" = { link = "Conditional" ;};
		"@keyword.exception" = { link = "Exception" ;};
		"@lsp.type.enum" = { link = "@type" ;};
		"@keyword.return" = { fg = "#e396a4" ;};
		"@keyword.repeat" = { link = "Repeat" ;};
		"@keyword.import" = { link = "Include" ;};
		"@lsp.type.enumMember" = { link = "@constant" ;};
		"@keyword.function" = { fg = "#e396a4" ;};
		LspCodeLensSeparator = { link = "LspCodeLens" ;};
		"@keyword.type" = { link = "Keyword" ;};
		"@lsp.type.unresolvedReference" = { link = "@error" ;};
		"@keyword" = { link = "Keyword" ;};
		"@operator" = { link = "Operator" ;};
		LspDiagnosticsUnderlineInformation = { sp = "#99c792"; underline = true ;};
		"@function.method.call" = { link = "Function" ;};
		"@function.method" = { link = "Function" ;};
		"@function.macro" = { fg = "#8ec07c" ;};
		"@function.call" = { link = "Function" ;};
		LspInlayHint = { bg = "#252626"; fg = "#595959" ;};
		LspDiagnosticsUnderlineError = { sp = "#ea6962"; underline = true ;};
		"@property" = { fg = "#7daea3" ;};
		"@attribute" = { link = "Constant" ;};
		"@type.definition" = { link = "Type" ;};
		"@type.builtin" = { fg = "#d8a657" ;};
		"@type" = { link = "Type" ;};
		"@number.float" = { link = "Float" ;};
		"@number" = { link = "Number" ;};
		"@boolean" = { link = "Boolean" ;};
		"@character.special" = { link = "SpecialChar" ;};
		"@character" = { link = "Character" ;};
		"@string.special.url" = { italic = true; underline = true; fg = "#eb7a73" ;};
		"@string.special.symbol" = { fg = "#eb7a73" ;};
		"@string.special.path" = { link = "Special" ;};
		"@string.special" = { link = "Special" ;};
		"@string.escape" = { fg = "#d3869b" ;};
		"@string.regexp" = { fg = "#e78a4e" ;};
		"@string.documentation" = { fg = "#8ec07c" ;};
		LspCodeLens = { fg = "#595959" ;};
		"@label" = { link = "Label" ;};
		"@module" = { italic = true; fg = "#7daea3" ;};
		"@lsp.type.selfKeyword" = { link = "@variable.builtin" ;};
		LspInfoBorder = { link = "FloatBorder" ;};
		"@constant" = { link = "Constant" ;};
		"@variable.member" = { fg = "#7daea3" ;};
		"@variable.parameter" = { fg = "#ea6962" ;};
		"@variable.builtin" = { fg = "#ea6962" ;};
		LspDiagnosticsUnderlineHint = { sp = "#8ec07c"; underline = true ;};
		SnacksIndentScope = { fg = "#ebdbb2" ;};
		SnacksIndent = { fg = "#292929" ;};
		SnacksDashboardTitle = { link = "Title" ;};
		SnacksDashboardSpecial = { link = "Special" ;};
		SnacksDashboardTerminal = { link = "SnacksDashboardNormal" ;};
		SnacksDashboardKey = { fg = "#e78a4e" ;};
		SnacksDashboardIcon = { bold = true; fg = "#d3869b" ;};
		SnacksDashboardHeader = { fg = "#83a598" ;};
		"@lsp.type.property" = { link = "@property" ;};
		"@lsp.type.parameter" = { link = "@parameter" ;};
		"@lsp.type.operator" = { link = "@operator" ;};
		"@lsp.type.number" = { link = "@number" ;};
		"@lsp.type.namespace" = { link = "@module" ;};
		"@lsp.type.keyword" = { link = "@keyword" ;};
		"@lsp.type.interface" = { fg = "#eb7a73" ;};
		"@lsp.type.formatSpecifier" = { link = "@punctuation.special" ;};
		SnacksNotifierTitleWarn = { italic = true; fg = "#d8a657" ;};
		SnacksNotifierBorderWarn = { fg = "#d8a657" ;};
		SnacksNotifierFooterWarn = { link = "DiagnosticWarn" ;};
		SnacksNotifierDebug = { fg = "#e78a4e" ;};
		SnacksNotifierIconDebug = { fg = "#e78a4e" ;};
		SnacksNotifierTitleDebug = { italic = true; fg = "#e78a4e" ;};
		SnacksNotifierBorderDebug = { fg = "#e78a4e" ;};
		SnacksNotifierFooterDebug = { link = "DiagnosticHint" ;};
		SnacksNotifierError = { fg = "#ea6962" ;};
		SnacksNotifierIconError = { fg = "#ea6962" ;};
		SnacksNotifierTitleError = { italic = true; fg = "#ea6962" ;};
		SnacksNotifierBorderError = { fg = "#ea6962" ;};
		SnacksNotifierFooterError = { link = "DiagnosticError" ;};
		SnacksNotifierTrace = { fg = "#eb7a73" ;};
		SnacksNotifierIconTrace = { fg = "#eb7a73" ;};
		SnacksNotifierTitleTrace = { italic = true; fg = "#eb7a73" ;};
		SnacksNotifierBorderTrace = { fg = "#eb7a73" ;};
		SnacksNotifierFooterTrace = { link = "DiagnosticHint" ;};
		SnacksDashboardNormal = { link = "Normal" ;};
		SnacksDashboardDesc = { fg = "#83a598" ;};
		SnacksDashboardFile = { fg = "#7daea3" ;};
		SnacksDashboardDir = { link = "NonText" ;};
		SnacksDashboardFooter = { italic = true; fg = "#d8a657" ;};
		ColorColumn = { bg = "#292929" ;};
		Conceal = { fg = "#928374" ;};
		Cursor = { bg = "#ebdbb2"; fg = "#1d2021" ;};
		lCursor = { bg = "#ebdbb2"; fg = "#1d2021" ;};
		CursorIM = { bg = "#ebdbb2"; fg = "#1d2021" ;};
		CursorColumn = { bg = "#191b1c" ;};
		CursorLine = { bg = "#252626" ;};
		Directory = { fg = "#83a598" ;};
		EndOfBuffer = { fg = "#1d2021" ;};
		ErrorMsg = { bold = true; italic = true; fg = "#ea6962" ;};
		"@constant.macro" = { link = "Macro" ;};
		"@lsp.type.typeAlias" = { link = "@type.definition" ;};
		VertSplit = { fg = "#141617" ;};
		Folded = { bg = "#404040"; fg = "#83a598" ;};
		FoldColumn = { fg = "#595959" ;};
		SignColumn = { fg = "#404040" ;};
		SignColumnSB = { fg = "#404040"; bg = "#141617" ;};
		Substitute = { fg = "#d3869b"; bg = "#404040" ;};
		LineNr = { fg = "#404040" ;};
		CursorLineNr = { fg = "#7daea3" ;};
		MatchParen = { fg = "#e78a4e"; bold = true; bg = "#404040" ;};
		ModeMsg = { bold = true; fg = "#ebdbb2" ;};
		MsgSeparator = { };
		MoreMsg = { fg = "#83a598" ;};
		NonText = { fg = "#595959" ;};
		Normal = { bg = "#1d2021"; fg = "#ebdbb2" ;};
		NormalNC = { bg = "#1d2021"; fg = "#ebdbb2" ;};
		"@keyword.modifier" = { link = "Keyword" ;};
		NormalSB = { bg = "#141617"; fg = "#ebdbb2" ;};
		NormalFloat = { bg = "#191b1c"; fg = "#ebdbb2" ;};
		"@keyword.operator" = { link = "Operator" ;};
		FloatBorder = { fg = "#83a598" ;};
		FloatTitle = { fg = "#bdae93" ;};
		Pmenu = { fg = "#a89984"; bg = "#252525" ;};
		"@keyword.debug" = { link = "Exception" ;};
		PmenuSel = { bold = true; bg = "#404040" ;};
		PmenuSbar = { bg = "#404040" ;};
		PmenuThumb = { bg = "#595959" ;};
		Question = { fg = "#83a598" ;};
		QuickFixLine = { bold = true; bg = "#404040" ;};
		Search = { fg = "#ebdbb2"; bg = "#425243" ;};
		IncSearch = { fg = "#191b1c"; bg = "#8DB687" ;};
		CurSearch = { fg = "#191b1c"; bg = "#ea6962" ;};
		SpecialKey = { link = "NonText" ;};
		"@comment.error" = { bg = "#ea6962"; fg = "#1d2021" ;};
		SpellBad = { undercurl = true; sp = "#ea6962" ;};
		"@comment.hint" = { bg = "#83a598"; fg = "#1d2021" ;};
		"@comment.todo" = { bg = "#eb7a73"; fg = "#1d2021" ;};
		SpellCap = { undercurl = true; sp = "#d8a657" ;};
		SpellLocal = { undercurl = true; sp = "#83a598" ;};
		SpellRare = { undercurl = true; sp = "#a9b665" ;};
		StatusLine = { bg = "#191b1c"; fg = "#ebdbb2" ;};
		StatusLineNC = { bg = "#191b1c"; fg = "#404040" ;};
		TabLine = { fg = "#595959"; bg = "#141617" ;};
		TabLineFill = { bg = "#191b1c" ;};
		TabLineSel = { link = "Normal" ;};
		TermCursor = { bg = "#eb7a73"; fg = "#1d2021" ;};
		TermCursorNC = { bg = "#a89984"; fg = "#1d2021" ;};
		Title = { bold = true; fg = "#83a598" ;};
		Visual = { bold = true; bg = "#404040" ;};
		VisualNOS = { bold = true; bg = "#404040" ;};
		Whitespace = { fg = "#404040" ;};
		WildMenu = { bg = "#595959" ;};
		WinBar = { fg = "#eb7a73" ;};
		WinBarNC = { link = "WinBar" ;};
		WinSeparator = { fg = "#141617" ;};
		Comment = { italic = true; fg = "#a89984" ;};
		SpecialComment = { link = "Special" ;};
		Special = { fg = "#d3869b" ;};
		Constant = { fg = "#e78a4e" ;};
		String = { fg = "#a9b665" ;};
		Character = { fg = "#8ec07c" ;};
		Number = { fg = "#e78a4e" ;};
		Float = { link = "Number" ;};
		Boolean = { fg = "#e78a4e" ;};
		Identifier = { fg = "#eb7a73" ;};
		Function = { fg = "#83a598" ;};
		Statement = { fg = "#e396a4" ;};
		Conditional = { italic = true; fg = "#e396a4" ;};
		Repeat = { fg = "#e396a4" ;};
		Label = { fg = "#89b482" ;};
		Operator = { fg = "#99c792" ;};
		Keyword = { fg = "#e396a4" ;};
		Exception = { fg = "#e396a4" ;};
		PreProc = { fg = "#d3869b" ;};
		Include = { fg = "#e396a4" ;};
		Define = { link = "PreProc" ;};
		Macro = { fg = "#e396a4" ;};
		PreCondit = { link = "PreProc" ;};
		StorageClass = { fg = "#d8a657" ;};
		Structure = { fg = "#d8a657" ;};
		Type = { fg = "#d8a657" ;};
		Typedef = { link = "Type" ;};
		SpecialChar = { link = "Special" ;};
		Tag = { bold = true; fg = "#7daea3" ;};
		Delimiter = { fg = "#a89984" ;};
		Debug = { link = "Special" ;};
		Underlined = { underline = true ;};
		Bold = { bold = true ;};
		Italic = { italic = true ;};
		Error = { fg = "#ea6962" ;};
		Todo = { fg = "#1d2021"; bold = true; bg = "#eb7a73" ;};
		qfLineNr = { fg = "#d8a657" ;};
		qfFileName = { fg = "#83a598" ;};
		htmlH1 = { bold = true; fg = "#d3869b" ;};
		htmlH2 = { bold = true; fg = "#83a598" ;};
		mkdCodeDelimiter = { fg = "#ebdbb2"; bg = "#1d2021" ;};
		mkdCodeStart = { bold = true; fg = "#eb7a73" ;};
		mkdCodeEnd = { bold = true; fg = "#eb7a73" ;};
		debugPC = { bg = "#141617" ;};
		debugBreakpoint = { fg = "#595959"; bg = "#1d2021" ;};
		illuminatedWord = { bg = "#404040" ;};
		illuminatedCurWord = { bg = "#404040" ;};
		diffAdded = { fg = "#a9b665" ;};
		diffRemoved = { fg = "#ea6962" ;};
		diffChanged = { fg = "#83a598" ;};
		diffOldFile = { fg = "#d8a657" ;};
		diffNewFile = { fg = "#e78a4e" ;};
		diffFile = { fg = "#83a598" ;};
		diffLine = { fg = "#595959" ;};
		diffIndexLine = { fg = "#8ec07c" ;};
		DiffAdd = { bg = "#363B2D" ;};
		DiffChange = { bg = "#242929" ;};
		DiffDelete = { bg = "#422D2D" ;};
		DiffText = { bg = "#3C4845" ;};
		healthError = { fg = "#ea6962" ;};
		healthSuccess = { fg = "#8ec07c" ;};
		healthWarning = { fg = "#d8a657" ;};
		LspReferenceText = { bg = "#404040" ;};
		LspReferenceRead = { bg = "#404040" ;};
		LspReferenceWrite = { bg = "#404040" ;};
		DiagnosticVirtualTextError = { fg = "#ea6962"; italic = true; bg = "#302727" ;};
		DiagnosticVirtualTextWarn = { fg = "#d8a657"; italic = true; bg = "#2F2D26" ;};
		DiagnosticVirtualTextInfo = { fg = "#99c792"; italic = true; bg = "#29302C" ;};
		DiagnosticVirtualTextHint = { fg = "#8ec07c"; italic = true; bg = "#282F2A" ;};
		DiagnosticVirtualTextOk = { fg = "#a9b665"; italic = true; bg = "#282F2A" ;};
		DiagnosticError = { fg = "#ea6962"; italic = true; bg = "NONE" ;};
		DiagnosticWarn = { fg = "#d8a657"; italic = true; bg = "NONE" ;};
		DiagnosticInfo = { fg = "#99c792"; italic = true; bg = "NONE" ;};
		DiagnosticHint = { fg = "#8ec07c"; italic = true; bg = "NONE" ;};
		DiagnosticOk = { fg = "#a9b665"; italic = true; bg = "NONE" ;};
		DiagnosticUnderlineError = { sp = "#ea6962"; underline = true ;};
		DiagnosticUnderlineWarn = { sp = "#d8a657"; underline = true ;};
		DiagnosticUnderlineInfo = { sp = "#99c792"; underline = true ;};
		DiagnosticUnderlineHint = { sp = "#8ec07c"; underline = true ;};
		DiagnosticUnderlineOk = { sp = "#a9b665"; underline = true ;};
		DiagnosticFloatingError = { fg = "#ea6962" ;};
		DiagnosticFloatingWarn = { fg = "#d8a657" ;};
		DiagnosticFloatingInfo = { fg = "#99c792" ;};
		DiagnosticFloatingHint = { fg = "#8ec07c" ;};
		DiagnosticFloatingOk = { fg = "#a9b665" ;};
		DiagnosticSignError = { fg = "#ea6962" ;};
		DiagnosticSignWarn = { fg = "#d8a657" ;};
		WarningMsg = { fg = "#d8a657" ;};
		DiagnosticSignHint = { fg = "#8ec07c" ;};
		DiagnosticSignOk = { fg = "#a9b665" ;};
		LspDiagnosticsDefaultError = { fg = "#ea6962" ;};
		LspDiagnosticsDefaultWarning = { fg = "#d8a657" ;};
		LspDiagnosticsDefaultInformation = { fg = "#99c792" ;};
		LspDiagnosticsDefaultHint = { fg = "#8ec07c" ;};
		LspSignatureActiveParameter = { bold = true; bg = "#292929" ;};
		LspDiagnosticsError = { fg = "#ea6962" ;};
		LspDiagnosticsWarning = { fg = "#d8a657" ;};
		LspDiagnosticsInformation = { fg = "#99c792" ;};
		LspDiagnosticsHint = { fg = "#8ec07c" ;};
		"@lsp.type.variable" = { };
		"@lsp.typemod.class.defaultLibrary" = { link = "@type.builtin" ;};
		"@lsp.typemod.enum.defaultLibrary" = { link = "@type.builtin" ;};
		"@lsp.typemod.enumMember.defaultLibrary" = { link = "@constant.builtin" ;};
		"@constant.builtin" = { fg = "#e78a4e" ;};
		"@lsp.typemod.function.defaultLibrary" = { link = "@function.builtin" ;};
		"@function.builtin" = { fg = "#e78a4e" ;};
		"@lsp.typemod.keyword.async" = { link = "@keyword.coroutine" ;};
		"@keyword.coroutine" = { link = "Keyword" ;};
		"@lsp.typemod.macro.defaultLibrary" = { link = "@function.builtin" ;};
		"@lsp.typemod.method.defaultLibrary" = { link = "@function.builtin" ;};
		"@lsp.typemod.operator.injected" = { link = "@operator" ;};
		"@lsp.typemod.string.injected" = { link = "@string" ;};
		"@string" = { link = "String" ;};
		"@lsp.typemod.type.defaultLibrary" = { link = "@type.builtin" ;};
		"@lsp.typemod.variable.defaultLibrary" = { link = "@variable.builtin" ;};
		"@lsp.typemod.variable.injected" = { link = "@variable" ;};
		"@variable" = { fg = "#ebdbb2" ;};
		AerialLine = { bg = "NONE"; fg = "#d8a657" ;};
		AerialGuide = { fg = "#a89984" ;};
		AerialBooleanIcon = { link = "@boolean" ;};
		AerialClassIcon = { link = "@type" ;};
		AerialConstantIcon = { link = "@constant" ;};
		AerialConstructorIcon = { link = "@constructor" ;};
		"@constructor" = { fg = "#89b482" ;};
		AerialFieldIcon = { link = "@field" ;};
		LspDiagnosticsUnderlineWarning = { sp = "#d8a657"; underline = true ;};
		AerialFunctionIcon = { link = "@function" ;};
		"@function" = { link = "Function" ;};
		AerialMethodIcon = { link = "@method" ;};
		LspDiagnosticsVirtualTextHint = { italic = true; fg = "#8ec07c" ;};
		AerialNamespaceIcon = { link = "@namespace" ;};
		LspDiagnosticsVirtualTextInformation = { italic = true; fg = "#99c792" ;};
		AerialNumberIcon = { link = "@number" ;};
		AerialOperatorIcon = { link = "@operator" ;};
		AerialTypeParameterIcon = { link = "@type" ;};
		AerialPropertyIcon = { link = "@property" ;};
		AerialStringIcon = { link = "@string" ;};
		AerialVariableIcon = { link = "@constant" ;};
		AerialEnumMemberIcon = { link = "@field" ;};
		AerialEnumIcon = { link = "@type" ;};
		AerialFileIcon = { link = "@text.uri" ;};
		LspDiagnosticsVirtualTextWarning = { italic = true; fg = "#d8a657" ;};
		AerialModuleIcon = { link = "@namespace" ;};
		AerialPackageIcon = { link = "@namespace" ;};
		AerialInterfaceIcon = { link = "@type" ;};
		AerialStructIcon = { link = "@type" ;};
		AerialEventIcon = { link = "@type" ;};
		AerialArrayIcon = { link = "@constant" ;};
		AerialObjectIcon = { link = "@type" ;};
		AerialKeyIcon = { link = "@type" ;};
		AerialNullIcon = { link = "@type" ;};
		BlinkCmpLabel = { fg = "#a89984" ;};
		BlinkCmpLabelDeprecated = { strikethrough = true; fg = "#595959" ;};
		LspDiagnosticsVirtualTextError = { italic = true; fg = "#ea6962" ;};
		BlinkCmpKind = { fg = "#83a598" ;};
		BlinkCmpMenu = { fg = "#ebdbb2" ;};
		BlinkCmpMenuBorder = { fg = "#83a598" ;};
		BlinkCmpDocBorder = { fg = "#83a598" ;};
		BlinkCmpSignatureHelpActiveParameter = { fg = "#e396a4" ;};
		BlinkCmpSignatureHelpBorder = { fg = "#83a598" ;};
		BlinkCmpLabelMatch = { bold = true; fg = "#ebdbb2" ;};
		BlinkCmpKindText = { fg = "#a9b665" ;};
		BlinkCmpKindMethod = { fg = "#83a598" ;};
		BlinkCmpKindFunction = { fg = "#83a598" ;};
		BlinkCmpKindConstructor = { fg = "#83a598" ;};
		BlinkCmpKindField = { fg = "#a9b665" ;};
		BlinkCmpKindVariable = { fg = "#eb7a73" ;};
		BlinkCmpKindClass = { fg = "#d8a657" ;};
		BlinkCmpKindInterface = { fg = "#d8a657" ;};
		BlinkCmpKindModule = { fg = "#83a598" ;};
		BlinkCmpKindProperty = { fg = "#83a598" ;};
		BlinkCmpKindUnit = { fg = "#a9b665" ;};
		BlinkCmpKindValue = { fg = "#e78a4e" ;};
		BlinkCmpKindEnum = { fg = "#d8a657" ;};
		BlinkCmpKindKeyword = { fg = "#e396a4" ;};
		BlinkCmpKindSnippet = { fg = "#eb7a73" ;};
		BlinkCmpKindColor = { fg = "#ea6962" ;};
		BlinkCmpKindFile = { fg = "#83a598" ;};
		BlinkCmpKindReference = { fg = "#ea6962" ;};
		BlinkCmpKindFolder = { fg = "#83a598" ;};
		BlinkCmpKindEnumMember = { fg = "#8ec07c" ;};
		BlinkCmpKindConstant = { fg = "#e78a4e" ;};
		BlinkCmpKindStruct = { fg = "#83a598" ;};
		BlinkCmpKindEvent = { fg = "#83a598" ;};
		BlinkCmpKindOperator = { fg = "#99c792" ;};
		BlinkCmpKindTypeParameter = { fg = "#ea6962" ;};
		BlinkCmpKindCopilot = { fg = "#8ec07c" ;};
		DapBreakpoint = { fg = "#ea6962" ;};
		DapBreakpointCondition = { fg = "#d8a657" ;};
		DapBreakpointRejected = { fg = "#e396a4" ;};
		DapLogPoint = { fg = "#99c792" ;};
		DapStopped = { fg = "#ea6962" ;};
		DapUIScope = { fg = "#99c792" ;};
		DapUIType = { fg = "#e396a4" ;};
		DapUIValue = { fg = "#99c792" ;};
		DapUIVariable = { fg = "#ebdbb2" ;};
		DapUIModifiedValue = { fg = "#e78a4e" ;};
		DapUIDecoration = { fg = "#99c792" ;};
		DapUIThread = { fg = "#a9b665" ;};
		DapUIStoppedThread = { fg = "#99c792" ;};
		DapUISource = { fg = "#7daea3" ;};
		DapUILineNumber = { fg = "#99c792" ;};
		DapUIFloatBorder = { link = "FloatBorder" ;};
		DapUIWatchesEmpty = { fg = "#ea6962" ;};
		DapUIWatchesValue = { fg = "#a9b665" ;};
		DapUIWatchesError = { fg = "#ea6962" ;};
		DapUIBreakpointsPath = { fg = "#99c792" ;};
		DapUIBreakpointsInfo = { fg = "#a9b665" ;};
		DapUIBreakpointsCurrentLine = { bold = true; fg = "#a9b665" ;};
		DapUIBreakpointsDisabledLine = { fg = "#4d4d4d" ;};
		DapUIStepOver = { fg = "#83a598" ;};
		DapUIStepOverNC = { link = "DapUIStepOver" ;};
		DapUIStepInto = { fg = "#83a598" ;};
		DapUIStepIntoNC = { link = "DapUIStepInto" ;};
		DapUIStepBack = { fg = "#83a598" ;};
		DapUIStepBackNC = { link = "DapUIStepBack" ;};
		DapUIStepOut = { fg = "#83a598" ;};
		DapUIStepOutNC = { link = "DapUIStepOut" ;};
		DapUIStop = { fg = "#ea6962" ;};
		DapUIStopNC = { link = "DapUIStop" ;};
		DapUIPlayPause = { fg = "#a9b665" ;};
		DapUIPlayPauseNC = { link = "DapUIPlayPause" ;};
		DapUIRestart = { fg = "#a9b665" ;};
		DapUIRestartNC = { link = "DapUIRestart" ;};
		DapUIUnavailable = { fg = "#404040" ;};
		DapUIUnavailableNC = { link = "DapUIUnavailable" ;};
		DapUIWinSelect = { fg = "#e78a4e" ;};
		DropBarMenuHoverEntry = { link = "Visual" ;};
		DropBarMenuHoverIcon = { reverse = true ;};
		DropBarMenuHoverSymbol = { bold = true ;};
		DropBarIconUISeparator = { fg = "#928374" ;};
		FlashBackdrop = { fg = "#595959" ;};
		FlashLabel = { fg = "#a9b665"; bold = true; bg = "#7daea3" ;};
		FlashMatch = { bg = "#7daea3"; fg = "#7daea3" ;};
		FlashCurrent = { bg = "#7daea3"; fg = "#e78a4e" ;};
		FlashPrompt = { link = "NormalFloat" ;};
		GrugFarResultsMatch = { link = "IncSearch" ;};
		MiniHipatternsFixme = { fg = "#1d2021"; bold = true; bg = "#ea6962" ;};
		MiniHipatternsHack = { fg = "#1d2021"; bold = true; bg = "#d8a657" ;};
		MiniHipatternsNote = { fg = "#1d2021"; bold = true; bg = "#99c792" ;};
		MiniHipatternsTodo = { fg = "#1d2021"; bold = true; bg = "#8ec07c" ;};
		MiniIconsAzure = { fg = "#89b482" ;};
		MiniIconsBlue = { fg = "#83a598" ;};
		MiniIconsCyan = { fg = "#8ec07c" ;};
		MiniIconsGreen = { fg = "#a9b665" ;};
		MiniIconsGrey = { fg = "#ebdbb2" ;};
		MiniIconsOrange = { fg = "#e78a4e" ;};
		MiniIconsPurple = { fg = "#e396a4" ;};
		MiniIconsRed = { fg = "#ea6962" ;};
		MiniIconsYellow = { fg = "#d8a657" ;};
		NoiceCmdline = { fg = "#ebdbb2" ;};
		NoiceCmdlineIcon = { italic = true; fg = "#99c792" ;};
		NoiceCmdlineIconSearch = { fg = "#d8a657" ;};
		NoiceCmdlinePopupBorder = { fg = "#7daea3" ;};
		NoiceCmdlinePopupBorderSearch = { fg = "#d8a657" ;};
		NoiceConfirmBorder = { fg = "#83a598" ;};
		NoiceMini = { blend = 0; fg = "#ebdbb2" ;};
		NvimSurroundHighlight = { underline = true; sp = "#e78a4e" ;};
		OverseerPENDING = { };
		DiagnosticSignInfo = { fg = "#99c792" ;};
		OverseerRUNNING = { fg = "#d8a657" ;};
		OverseerSUCCESS = { fg = "#a9b665" ;};
		OverseerCANCELED = { fg = "#a89984" ;};
		OverseerFAILURE = { fg = "#ea6962" ;};
		OverseerTask = { fg = "#83a598" ;};
		OverseerTaskBorder = { fg = "#99c792" ;};
		OverseerOutput = { fg = "#ebdbb2" ;};
		OverseerComponent = { fg = "#d8a657" ;};
		OverseerField = { fg = "#a9b665" ;};
		RainbowDelimiterRed = { fg = "#ea6962" ;};
		RainbowDelimiterYellow = { fg = "#d8a657" ;};
		RainbowDelimiterBlue = { fg = "#83a598" ;};
		RainbowDelimiterOrange = { fg = "#e78a4e" ;};
		RainbowDelimiterGreen = { fg = "#a9b665" ;};
		RainbowDelimiterViolet = { fg = "#e396a4" ;};
		RainbowDelimiterCyan = { fg = "#8ec07c" ;};
		RenderMarkdownCode = { bg = "#191b1c" ;};
		RenderMarkdownCodeInline = { bg = "#292929" ;};
		RenderMarkdownBullet = { fg = "#99c792" ;};
		RenderMarkdownTableHead = { fg = "#83a598" ;};
		RenderMarkdownTableRow = { fg = "#7daea3" ;};
		RenderMarkdownSuccess = { fg = "#a9b665" ;};
		RenderMarkdownInfo = { fg = "#99c792" ;};
		RenderMarkdownHint = { fg = "#8ec07c" ;};
		RenderMarkdownWarn = { fg = "#d8a657" ;};
		RenderMarkdownError = { fg = "#ea6962" ;};
		SnacksNormal = { link = "NormalFloat" ;};
		SnacksWinBar = { link = "Title" ;};
		SnacksBackdrop = { fg = "#595959" ;};
		SnacksNormalNC = { link = "NormalFloat" ;};
		SnacksWinBarNC = { link = "SnacksWinBar" ;};
		SnacksNotifierInfo = { fg = "#83a598" ;};
		SnacksNotifierIconInfo = { fg = "#83a598" ;};
		SnacksNotifierTitleInfo = { italic = true; fg = "#83a598" ;};
		SnacksNotifierFooterInfo = { link = "DiagnosticInfo" ;};
		SnacksNotifierBorderInfo = { fg = "#83a598" ;};
		SnacksNotifierWarn = { fg = "#d8a657" ;};
		SnacksNotifierIconWarn = { fg = "#d8a657" ;};
		"@lsp.type.escapeSequence" = { link = "@string.escape" ;};
	};

	programs.nixvim.globals = {
		terminal_color_8 = "#928374";
		terminal_color_1 = "#ea6962";
		terminal_color_9 = "#ea6962";
		terminal_color_2 = "#a9b665";
		terminal_color_10 = "#a9b665";
		terminal_color_3 = "#d8a657";
		terminal_color_11 = "#d8a657";
		terminal_color_4 = "#83a598";
		terminal_color_12 = "#83a598";
		terminal_color_5 = "#d3869b";
		terminal_color_13 = "#d3869b";
		terminal_color_6 = "#99c792";
		terminal_color_14 = "#99c792";
		terminal_color_7 = "#ebdbb2";
		terminal_color_15 = "#ebdbb2";
		terminal_color_0 = "#595959";
	};
}