{
	programs.nixvim.highlight = {
		"@keyword.import" = { fg = "#C586C0"; bg = "NONE" ;};
		"@operator" = { fg = "#D4D4D4"; bg = "NONE" ;};
		"@type" = { fg = "#4EC9B0"; bg = "NONE" ;};
		"@type.qualifier" = { fg = "#569CD6"; bg = "NONE" ;};
		"@structure" = { fg = "#9CDCFE"; bg = "NONE" ;};
		"@tag" = { fg = "#569CD6"; bg = "NONE" ;};
		"@tag.builtin" = { fg = "#569CD6"; bg = "NONE" ;};
		"@tag.delimiter" = { fg = "#808080"; bg = "NONE" ;};
		"@tag.attribute" = { fg = "#9CDCFE"; bg = "NONE" ;};
		"@text" = { fg = "#D4D4D4"; bg = "NONE" ;};
		"@markup.strong" = { fg = "#569CD6"; bold = true ;};
		"@markup.italic" = { italic = true; fg = "#D4D4D4"; bg = "NONE" ;};
		"@markup.underline" = { underline = true; fg = "#D7BA7D"; bg = "NONE" ;};
		"@lsp.type.comment.cpp" = { fg = "#51504F"; bg = "NONE" ;};
		"@event" = { link = "Identifier" ;};
		"@interface" = { link = "Identifier" ;};
		"@modifier" = { link = "Identifier" ;};
		"@regexp" = { fg = "#e75a7c"; bg = "NONE" ;};
		"@decorator" = { link = "Identifier" ;};
		markdownBold = { fg = "#569CD6"; bold = true ;};
		markdownCode = { fg = "#CE9178"; bg = "NONE" ;};
		markdownRule = { fg = "#569CD6"; bold = true ;};
		markdownCodeDelimiter = { fg = "#D4D4D4"; bg = "NONE" ;};
		markdownHeadingDelimiter = { fg = "#569CD6"; bg = "NONE" ;};
		markdownFootnote = { fg = "#CE9178"; bg = "NONE" ;};
		markdownFootnoteDefinition = { fg = "#CE9178" ;};
		markdownUrl = { underline = true; fg = "#D4D4D4"; bg = "NONE" ;};
		markdownLinkText = { fg = "#CE9178" ;};
		markdownEscape = { fg = "#CE9178" ;};
		"@markup.environment.name.latex" = { fg = "#9CDCFE" ;};
		"@function.macro.latex" = { fg = "#C586C0" ;};
		"@operator.latex" = { fg = "#569CD6" ;};
		"@punctuation.special.latex" = { fg = "#569CD6" ;};
		"@string.latex" = { fg = "#4EC9B0" ;};
		GitSignsAdd = { fg = "#6A9955" ;};
		GitSignsChange = { fg = "#DCDCAA" ;};
		GitSignsDelete = { fg = "#e75a7c" ;};
		GitSignsAddLn = { fg = "#1F1F1F"; bg = "#6A9955" ;};
		GitSignsChangeLn = { fg = "#1F1F1F"; bg = "#DCDCAA" ;};
		GitSignsDeleteLn = { fg = "#1F1F1F"; bg = "#e75a7c" ;};
		DiagnosticOk = { fg = "#4EC9B0"; bg = "NONE" ;};
		DiagnosticError = { fg = "#e75a7c" ;};
		DiagnosticWarn = { fg = "#DCDCAA" ;};
		DiagnosticInfo = { fg = "#569CD6" ;};
		DiagnosticHint = { fg = "#569CD6" ;};
		DiagnosticUnderlineError = { sp = "#e75a7c"; undercurl = true ;};
		DiagnosticUnderlineWarn = { sp = "#DCDCAA"; undercurl = true ;};
		DiagnosticUnderlineInfo = { sp = "#569CD6"; undercurl = true ;};
		DiagnosticUnderlineHint = { sp = "#569CD6"; undercurl = true ;};
		LspReferenceText = { bg = "#343B41" ;};
		LspReferenceRead = { bg = "#343B41" ;};
		LspReferenceWrite = { bg = "#343B41" ;};
		LspInlayHint = { fg = "#8D949D"; bg = "#353738" ;};
		AerialArrayIcon = { link = "Type" ;};
		AerialBooleanIcon = { link = "Boolean" ;};
		AerialClassIcon = { link = "Include" ;};
		AerialConstantIcon = { link = "Constant" ;};
		AerialConstructorIcon = { link = "@constructor" ;};
		AerialEnumIcon = { link = "@number" ;};
		AerialEnumMemberIcon = { link = "@number" ;};
		AerialEventIcon = { link = "@constant" ;};
		AerialFieldIcon = { link = "@variable.member" ;};
		AerialFileIcon = { link = "Tag" ;};
		AerialFunctionIcon = { link = "Function" ;};
		AerialInterfaceIcon = { link = "Type" ;};
		AerialKeyIcon = { link = "Constant" ;};
		AerialMethodIcon = { link = "Function" ;};
		AerialModuleIcon = { link = "Exception" ;};
		AerialNamespaceIcon = { link = "Include" ;};
		AerialNullIcon = { link = "Constant" ;};
		AerialNumberIcon = { link = "Number" ;};
		AerialObjectIcon = { link = "Type" ;};
		AerialOperatorIcon = { link = "Operator" ;};
		AerialPackageIcon = { link = "Label" ;};
		AerialPropertyIcon = { link = "@property" ;};
		AerialStringIcon = { link = "String" ;};
		AerialStructIcon = { link = "Type" ;};
		AerialTypeParameterIcon = { link = "Type" ;};
		AerialVariableIcon = { link = "@variable" ;};
		DapBreakpoint = { fg = "#81b88b" ;};
		DapLogPoint = { fg = "#c74e39" ;};
		DapStopped = { fg = "#e2c08d" ;};
		DapUIBreakpointsCurrentLine = { fg = "#4EC9B0"; bold = true ;};
		DapUIBreakpointsDisabledLine = { fg = "#51504F" ;};
		DapUIBreakpointsInfo = { fg = "#4EC9B0" ;};
		DapUIBreakpointsLine = { fg = "#C586C0" ;};
		DapUIBreakpointsPath = { fg = "#C586C0" ;};
		DapUICurrentFrameName = { fg = "#4EC9B0"; bold = true ;};
		DapUIDecoration = { fg = "#C586C0" ;};
		DapUIFloatBorder = { fg = "#C586C0" ;};
		DapUILineNumber = { fg = "#C586C0" ;};
		DapUIModifiedValue = { fg = "#C586C0"; bold = true ;};
		DapUIPlayPause = { fg = "#4EC9B0" ;};
		DapUIPlayPauseNC = { fg = "#4EC9B0" ;};
		DapUIRestart = { fg = "#4EC9B0" ;};
		DapUIRestartNC = { fg = "#4EC9B0" ;};
		DapUIScope = { fg = "#C586C0" ;};
		DapUISource = { fg = "#18a2fe" ;};
		DapUIStepBack = { fg = "#C586C0" ;};
		DapUIStepBackNC = { fg = "#C586C0" ;};
		DapUIStepInto = { fg = "#C586C0" ;};
		DapUIStepIntoNC = { fg = "#C586C0" ;};
		DapUIStepOut = { fg = "#C586C0" ;};
		DapUIStepOutNC = { fg = "#C586C0" ;};
		DapUIStepOver = { fg = "#C586C0" ;};
		DapUIStepOverNC = { fg = "#C586C0" ;};
		DapUIStop = { fg = "#e75a7c" ;};
		DapUIStopNC = { fg = "#e75a7c" ;};
		DapUIStoppedThread = { fg = "#C586C0" ;};
		DapUIThread = { fg = "#4EC9B0" ;};
		DapUIType = { fg = "#C586C0" ;};
		DapUIUnavailable = { fg = "#51504F" ;};
		DapUIUnavailableNC = { fg = "#51504F" ;};
		DapUIWatchesEmpty = { fg = "#51504F" ;};
		DapUIWatchesError = { fg = "#e75a7c" ;};
		DapUIWatchesValue = { fg = "#4EC9B0" ;};
		DapUIWinSelect = { fg = "#C586C0"; bold = true ;};
		RainbowDelimiterRed = { fg = "#E06C75" ;};
		RainbowDelimiterYellow = { fg = "#E5C07B" ;};
		RainbowDelimiterBlue = { fg = "#61AFEF" ;};
		RainbowDelimiterGreen = { fg = "#98C379" ;};
		RainbowDelimiterCyan = { };
		RainbowDelimiterOrange = { fg = "#D19A66" ;};
		RainbowDelimiterViolet = { fg = "#C678DD" ;};
		WarningMsg = { bold = true; fg = "#e75a7c"; bg = "#1F1F1F" ;};
		"@keyword.exception" = { fg = "#C586C0"; bg = "NONE" ;};
		"@keyword.return" = { fg = "#C586C0"; bg = "NONE" ;};
		"@keyword.repeat" = { fg = "#C586C0"; bg = "NONE" ;};
		"@keyword.conditional" = { fg = "#C586C0"; bg = "NONE" ;};
		"@keyword" = { fg = "#569CD6"; bg = "NONE" ;};
		"@label" = { fg = "#9CDCFE"; bg = "NONE" ;};
		"@constructor" = { fg = "#569CD6"; bg = "NONE" ;};
		"@property" = { fg = "#9CDCFE"; bg = "NONE" ;};
		"@variable.member" = { fg = "#9CDCFE"; bg = "NONE" ;};
		"@lsp.type.typeParameter" = { link = "@type" ;};
		"@lsp.type.type" = { link = "@type" ;};
		"@lsp.typemod.type.defaultLibrary" = { link = "@type.builtin" ;};
		"@type.builtin" = { fg = "#569CD6"; bg = "NONE" ;};
		"@lsp.type.comment.c" = { fg = "#51504F"; bg = "NONE" ;};
		"@lsp.typemod.keyword.controlFlow" = { fg = "#C586C0"; bg = "NONE" ;};
		"@lsp.type.keyword" = { link = "@keyword" ;};
		"@lsp.type.member" = { link = "@function" ;};
		"@lsp.typemod.variable.constant" = { link = "@constant" ;};
		"@lsp.typemod.property.readonly" = { link = "@constant" ;};
		Normal = { fg = "#D4D4D4"; bg = "#1F1F1F" ;};
		"@lsp.typemod.variable.readonly" = { link = "@constant" ;};
		"@lsp.type.enumMember" = { link = "@constant" ;};
		ColorColumn = { fg = "NONE"; bg = "#222222" ;};
		Cursor = { fg = "#51504F"; bg = "#AEAFAD" ;};
		CursorLine = { bg = "#222222" ;};
		CursorColumn = { fg = "NONE"; bg = "#222222" ;};
		Directory = { fg = "#569CD6"; bg = "#1F1F1F" ;};
		DiffAdd = { fg = "NONE"; bg = "#4B5632" ;};
		DiffChange = { fg = "NONE"; bg = "#4B1818" ;};
		DiffDelete = { fg = "NONE"; bg = "#6F1313" ;};
		DiffText = { fg = "NONE"; bg = "#6F1313" ;};
		EndOfBuffer = { fg = "#1F1F1F"; bg = "NONE" ;};
		ErrorMsg = { fg = "#e75a7c"; bg = "#1F1F1F" ;};
		VertSplit = { fg = "#444444"; bg = "#1F1F1F" ;};
		WinSeparator = { link = "VertSplit" ;};
		"@lsp.type.macro" = { link = "@constant" ;};
		Folded = { fg = "NONE"; bg = "#202d39" ;};
		FoldColumn = { fg = "#5A5A5A"; bg = "#1F1F1F" ;};
		SignColumn = { fg = "NONE"; bg = "#1F1F1F" ;};
		IncSearch = { fg = "NONE"; bg = "#515c6a" ;};
		LineNr = { fg = "#5A5A5A"; bg = "#1F1F1F" ;};
		CursorLineNr = { fg = "#BBBBBB"; bg = "#1F1F1F" ;};
		MatchParen = { fg = "NONE"; bg = "#51504F" ;};
		ModeMsg = { fg = "#D4D4D4"; bg = "#252526" ;};
		MoreMsg = { fg = "#D4D4D4"; bg = "#252526" ;};
		NonText = { fg = "#5A5A5A"; bg = "NONE" ;};
		Pmenu = { fg = "#BBBBBB"; bg = "#272727" ;};
		PmenuSel = { fg = "#BBBBBB"; bg = "#004b72" ;};
		PmenuSbar = { fg = "NONE"; bg = "#343B41" ;};
		PmenuThumb = { fg = "NONE"; bg = "#BBBBBB" ;};
		Question = { fg = "#569CD6"; bg = "#1F1F1F" ;};
		Search = { fg = "NONE"; bg = "#613315" ;};
		SpecialKey = { fg = "#569CD6"; bg = "NONE" ;};
		StatusLine = { fg = "#D4D4D4"; bg = "#373737" ;};
		StatusLineNC = { fg = "#D4D4D4"; bg = "#252526" ;};
		TabLine = { fg = "#D4D4D4"; bg = "#2D2D2D" ;};
		TabLineFill = { fg = "#D4D4D4"; bg = "#252526" ;};
		TabLineSel = { fg = "#D4D4D4"; bg = "#1F1F1F" ;};
		Title = { bold = true; fg = "NONE"; bg = "NONE" ;};
		"@markup.raw.markdown_inline" = { fg = "#CE9178"; bg = "NONE" ;};
		Visual = { fg = "NONE"; bg = "#264F78" ;};
		VisualNOS = { fg = "NONE"; bg = "#264F78" ;};
		WildMenu = { fg = "NONE"; bg = "#264F78" ;};
		Comment = { italic = true; fg = "#6A9955"; bg = "NONE" ;};
		"@markup.raw.markdown" = { fg = "#CE9178"; bg = "NONE" ;};
		Constant = { fg = "#569CD6"; bg = "NONE" ;};
		String = { fg = "#CE9178"; bg = "NONE" ;};
		Character = { fg = "#CE9178"; bg = "NONE" ;};
		Number = { fg = "#B5CEA8"; bg = "NONE" ;};
		Boolean = { fg = "#569CD6"; bg = "NONE" ;};
		Float = { fg = "#B5CEA8"; bg = "NONE" ;};
		Identifier = { fg = "#9CDCFE"; bg = "NONE" ;};
		Function = { fg = "#DCDCAA"; bg = "NONE" ;};
		Statement = { fg = "#C586C0"; bg = "NONE" ;};
		Conditional = { fg = "#C586C0"; bg = "NONE" ;};
		Repeat = { fg = "#C586C0"; bg = "NONE" ;};
		Label = { fg = "#C586C0"; bg = "NONE" ;};
		Operator = { fg = "#D4D4D4"; bg = "NONE" ;};
		Keyword = { fg = "#C586C0"; bg = "NONE" ;};
		Exception = { fg = "#C586C0"; bg = "NONE" ;};
		PreProc = { fg = "#C586C0"; bg = "NONE" ;};
		Include = { fg = "#C586C0"; bg = "NONE" ;};
		Define = { fg = "#C586C0"; bg = "NONE" ;};
		Macro = { fg = "#C586C0"; bg = "NONE" ;};
		Type = { fg = "#569CD6"; bg = "NONE" ;};
		StorageClass = { fg = "#569CD6"; bg = "NONE" ;};
		Structure = { fg = "#4EC9B0"; bg = "NONE" ;};
		Typedef = { fg = "#569CD6"; bg = "NONE" ;};
		Special = { fg = "#D7BA7D"; bg = "NONE" ;};
		SpecialChar = { fg = "#D4D4D4"; bg = "NONE" ;};
		Tag = { fg = "#D4D4D4"; bg = "NONE" ;};
		Delimiter = { fg = "#D4D4D4"; bg = "NONE" ;};
		SpecialComment = { fg = "#6A9955"; bg = "NONE" ;};
		Debug = { fg = "#D4D4D4"; bg = "NONE" ;};
		Underlined = { underline = true; fg = "NONE"; bg = "NONE" ;};
		"@markup.raw" = { fg = "#D4D4D4"; bg = "NONE" ;};
		Conceal = { fg = "#D4D4D4"; bg = "#1F1F1F" ;};
		Ignore = { fg = "#D4D4D4"; bg = "NONE" ;};
		Error = { sp = "#e75a7c"; undercurl = true; fg = "#e75a7c"; bg = "#1F1F1F" ;};
		"@markup.heading" = { fg = "#569CD6"; bold = true ;};
		"@markup.strikethrough" = { strikethrough = true; fg = "#D4D4D4"; bg = "NONE" ;};
		Todo = { bold = true; fg = "#D7BA7D"; bg = "#1F1F1F" ;};
		SpellBad = { undercurl = true; fg = "NONE"; sp = "#e75a7c" ;};
		SpellCap = { undercurl = true; fg = "NONE"; sp = "#DCDCAA" ;};
		SpellRare = { undercurl = true; fg = "NONE"; sp = "#646695" ;};
		SpellLocal = { undercurl = true; fg = "NONE"; sp = "#569CD6" ;};
		Whitespace = { fg = "#5A5A5A" ;};
		NormalFloat = { bg = "#272727" ;};
		WinBar = { bold = true; fg = "#D4D4D4"; bg = "#1F1F1F" ;};
		WinBarNc = { fg = "#D4D4D4"; bg = "#1F1F1F" ;};
		QuickFixLine = { bold = true ;};
		"@error" = { fg = "#e75a7c"; bg = "NONE" ;};
		"@punctuation.bracket" = { fg = "#D4D4D4"; bg = "NONE" ;};
		"@punctuation.special" = { fg = "#D4D4D4"; bg = "NONE" ;};
		"@punctuation.delimiter" = { fg = "#D4D4D4"; bg = "NONE" ;};
		"@comment" = { italic = true; fg = "#6A9955"; bg = "NONE" ;};
		"@comment.note" = { bold = true; fg = "#4EC9B0"; bg = "NONE" ;};
		"@comment.warning" = { bold = true; fg = "#D7BA7D"; bg = "NONE" ;};
		"@comment.error" = { bold = true; fg = "#e75a7c"; bg = "NONE" ;};
		"@constant" = { fg = "#4FC1FF"; bg = "NONE" ;};
		"@constant.builtin" = { fg = "#569CD6"; bg = "NONE" ;};
		"@constant.macro" = { fg = "#4EC9B0"; bg = "NONE" ;};
		"@string.regexp" = { fg = "#CE9178"; bg = "NONE" ;};
		"@string" = { fg = "#CE9178"; bg = "NONE" ;};
		"@character" = { fg = "#CE9178"; bg = "NONE" ;};
		"@number" = { fg = "#B5CEA8"; bg = "NONE" ;};
		"@number.float" = { fg = "#B5CEA8"; bg = "NONE" ;};
		"@boolean" = { fg = "#569CD6"; bg = "NONE" ;};
		"@annotation" = { fg = "#DCDCAA"; bg = "NONE" ;};
		"@attribute" = { fg = "#DCDCAA"; bg = "NONE" ;};
		"@attribute.builtin" = { fg = "#4EC9B0"; bg = "NONE" ;};
		"@module" = { fg = "#4EC9B0"; bg = "NONE" ;};
		"@function" = { fg = "#DCDCAA"; bg = "NONE" ;};
		"@function.builtin" = { fg = "#DCDCAA"; bg = "NONE" ;};
		"@function.macro" = { fg = "#DCDCAA"; bg = "NONE" ;};
		"@function.method" = { fg = "#DCDCAA"; bg = "NONE" ;};
		"@define" = { fg = "#C586C0"; bg = "NONE" ;};
		"@variable" = { fg = "#9CDCFE"; bg = "NONE" ;};
		"@variable.builtin" = { fg = "#569CD6"; bg = "NONE" ;};
		"@variable.parameter" = { fg = "#9CDCFE"; bg = "NONE" ;};
		"@variable.parameter.reference" = { fg = "#9CDCFE"; bg = "NONE" ;};
		"@markup.link.label" = { underline = false; fg = "#9CDCFE"; bg = "NONE" ;};
		"@markup.link.url" = { underline = false; fg = "#D4D4D4"; bg = "NONE" ;};
		"@markup.list.checked" = { link = "Todo" ;};
		"@markup.list.unchecked" = { link = "Todo" ;};
		"@textReference" = { fg = "#CE9178" ;};
		"@stringEscape" = { fg = "#CE9178"; bold = true ;};
		"@diff.plus" = { link = "DiffAdd" ;};
		"@diff.minus" = { link = "DiffDelete" ;};
		"@diff.delta" = { link = "DiffChange" ;};
	};

	programs.nixvim.globals = {
		terminal_color_14 = "#4EC9B0";
		terminal_color_0 = "#1F1F1F";
		terminal_color_8 = "#808080";
		terminal_color_7 = "#D4D4D4";
		terminal_color_15 = "#D4D4D4";
		terminal_color_1 = "#e75a7c";
		terminal_color_9 = "#e75a7c";
		terminal_color_2 = "#6A9955";
		terminal_color_10 = "#6A9955";
		terminal_color_3 = "#DCDCAA";
		terminal_color_11 = "#DCDCAA";
		terminal_color_4 = "#569CD6";
		terminal_color_12 = "#569CD6";
		terminal_color_5 = "#C586C0";
		terminal_color_13 = "#C586C0";
		terminal_color_6 = "#4EC9B0";
	};
}