{
	programs.nixvim.highlight = {
		Normal = { bg = "#1F1F1F"; fg = "#D4D4D4" ;};
		ColorColumn = { bg = "#222222"; fg = "NONE" ;};
		Cursor = { bg = "#AEAFAD"; fg = "#51504F" ;};
		CursorLine = { bg = "#222222" ;};
		CursorColumn = { bg = "#222222"; fg = "NONE" ;};
		Directory = { bg = "#1F1F1F"; fg = "#569CD6" ;};
		DiffAdd = { bg = "#4B5632"; fg = "NONE" ;};
		DiffChange = { bg = "#4B1818"; fg = "NONE" ;};
		DiffDelete = { bg = "#6F1313"; fg = "NONE" ;};
		DiffText = { bg = "#6F1313"; fg = "NONE" ;};
		EndOfBuffer = { bg = "NONE"; fg = "#1F1F1F" ;};
		ErrorMsg = { bg = "#1F1F1F"; fg = "#F44747" ;};
		VertSplit = { bg = "#1F1F1F"; fg = "#444444" ;};
		WinSeparator = { link = "VertSplit" ;};
		Folded = { bg = "#202d39"; fg = "NONE" ;};
		FoldColumn = { bg = "#1F1F1F"; fg = "#5A5A5A" ;};
		SignColumn = { bg = "#1F1F1F"; fg = "NONE" ;};
		IncSearch = { bg = "#515c6a"; fg = "NONE" ;};
		LineNr = { bg = "#1F1F1F"; fg = "#5A5A5A" ;};
		CursorLineNr = { bg = "#1F1F1F"; fg = "#BBBBBB" ;};
		MatchParen = { bg = "#51504F"; fg = "NONE" ;};
		ModeMsg = { bg = "#252526"; fg = "#D4D4D4" ;};
		MoreMsg = { bg = "#252526"; fg = "#D4D4D4" ;};
		NonText = { bg = "NONE"; fg = "#5A5A5A" ;};
		Pmenu = { bg = "#272727"; fg = "#BBBBBB" ;};
		PmenuSel = { bg = "#004b72"; fg = "#BBBBBB" ;};
		PmenuSbar = { bg = "#343B41"; fg = "NONE" ;};
		PmenuThumb = { bg = "#BBBBBB"; fg = "NONE" ;};
		Question = { bg = "#1F1F1F"; fg = "#569CD6" ;};
		Search = { bg = "#613315"; fg = "NONE" ;};
		SpecialKey = { bg = "NONE"; fg = "#569CD6" ;};
		StatusLine = { bg = "#373737"; fg = "#D4D4D4" ;};
		StatusLineNC = { bg = "#252526"; fg = "#D4D4D4" ;};
		TabLine = { bg = "#2D2D2D"; fg = "#D4D4D4" ;};
		TabLineFill = { bg = "#252526"; fg = "#D4D4D4" ;};
		TabLineSel = { bg = "#1F1F1F"; fg = "#D4D4D4" ;};
		Title = { bg = "NONE"; bold = true; fg = "NONE" ;};
		Visual = { bg = "#264F78"; fg = "NONE" ;};
		VisualNOS = { bg = "#264F78"; fg = "NONE" ;};
		WildMenu = { bg = "#264F78"; fg = "NONE" ;};
		Comment = { bg = "NONE"; italic = true; fg = "#6A9955" ;};
		Constant = { bg = "NONE"; fg = "#569CD6" ;};
		String = { bg = "NONE"; fg = "#CE9178" ;};
		Character = { bg = "NONE"; fg = "#CE9178" ;};
		Number = { bg = "NONE"; fg = "#B5CEA8" ;};
		Boolean = { bg = "NONE"; fg = "#569CD6" ;};
		Float = { bg = "NONE"; fg = "#B5CEA8" ;};
		Identifier = { bg = "NONE"; fg = "#9CDCFE" ;};
		Function = { bg = "NONE"; fg = "#DCDCAA" ;};
		Statement = { bg = "NONE"; fg = "#C586C0" ;};
		Conditional = { bg = "NONE"; fg = "#C586C0" ;};
		Repeat = { bg = "NONE"; fg = "#C586C0" ;};
		Label = { bg = "NONE"; fg = "#C586C0" ;};
		Operator = { bg = "NONE"; fg = "#D4D4D4" ;};
		Keyword = { bg = "NONE"; fg = "#C586C0" ;};
		Exception = { bg = "NONE"; fg = "#C586C0" ;};
		PreProc = { bg = "NONE"; fg = "#C586C0" ;};
		Include = { bg = "NONE"; fg = "#C586C0" ;};
		Define = { bg = "NONE"; fg = "#C586C0" ;};
		Macro = { bg = "NONE"; fg = "#C586C0" ;};
		Type = { bg = "NONE"; fg = "#569CD6" ;};
		StorageClass = { bg = "NONE"; fg = "#569CD6" ;};
		Structure = { bg = "NONE"; fg = "#4EC9B0" ;};
		Typedef = { bg = "NONE"; fg = "#569CD6" ;};
		Special = { bg = "NONE"; fg = "#D7BA7D" ;};
		SpecialChar = { bg = "NONE"; fg = "#D4D4D4" ;};
		Tag = { bg = "NONE"; fg = "#D4D4D4" ;};
		Delimiter = { bg = "NONE"; fg = "#D4D4D4" ;};
		SpecialComment = { bg = "NONE"; fg = "#6A9955" ;};
		Debug = { bg = "NONE"; fg = "#D4D4D4" ;};
		Underlined = { bg = "NONE"; underline = true; fg = "NONE" ;};
		Conceal = { bg = "#1F1F1F"; fg = "#D4D4D4" ;};
		Ignore = { bg = "NONE"; fg = "#D4D4D4" ;};
		Error = { bg = "#1F1F1F"; sp = "#F44747"; undercurl = true; fg = "#F44747" ;};
		Todo = { bg = "#1F1F1F"; bold = true; fg = "#D7BA7D" ;};
		SpellBad = { sp = "#F44747"; undercurl = true; fg = "NONE" ;};
		SpellCap = { sp = "#DCDCAA"; undercurl = true; fg = "NONE" ;};
		AerialVariableIcon = { link = "@variable" ;};
		DapBreakpoint = { fg = "#81b88b" ;};
		DapLogPoint = { fg = "#c74e39" ;};
		DapStopped = { fg = "#e2c08d" ;};
		DapUIBreakpointsCurrentLine = { bold = true; fg = "#4EC9B0" ;};
		DapUIBreakpointsDisabledLine = { fg = "#51504F" ;};
		DapUIBreakpointsInfo = { fg = "#4EC9B0" ;};
		DapUIBreakpointsLine = { fg = "#C586C0" ;};
		DapUIBreakpointsPath = { fg = "#C586C0" ;};
		DapUICurrentFrameName = { bold = true; fg = "#4EC9B0" ;};
		DapUIDecoration = { fg = "#C586C0" ;};
		DapUIFloatBorder = { fg = "#C586C0" ;};
		DapUILineNumber = { fg = "#C586C0" ;};
		DapUIModifiedValue = { bold = true; fg = "#C586C0" ;};
		DapUIPlayPause = { fg = "#4EC9B0" ;};
		DapUIPlayPauseNC = { fg = "#4EC9B0" ;};
		DapUIRestart = { fg = "#4EC9B0" ;};
		DapUIRestartNC = { fg = "#4EC9B0" ;};
		DapUIScope = { fg = "#C586C0" ;};
		DapUISource = { fg = "#18a2fe" ;};
		DapUIStepBack = { fg = "#C586C0" ;};
		DapUIStepBackNC = { fg = "#C586C0" ;};
		DapUIStepInto = { fg = "#C586C0" ;};
		DapUIStepIntoNC = { fg = "#C586C0" ;};
		DapUIStepOut = { fg = "#C586C0" ;};
		DapUIStepOutNC = { fg = "#C586C0" ;};
		DapUIStepOver = { fg = "#C586C0" ;};
		DapUIStepOverNC = { fg = "#C586C0" ;};
		DapUIStop = { fg = "#F44747" ;};
		DapUIStopNC = { fg = "#F44747" ;};
		DapUIStoppedThread = { fg = "#C586C0" ;};
		DapUIThread = { fg = "#4EC9B0" ;};
		DapUIType = { fg = "#C586C0" ;};
		DapUIUnavailable = { fg = "#51504F" ;};
		DapUIUnavailableNC = { fg = "#51504F" ;};
		DapUIWatchesEmpty = { fg = "#51504F" ;};
		DapUIWatchesError = { fg = "#F44747" ;};
		DapUIWatchesValue = { fg = "#4EC9B0" ;};
		DapUIWinSelect = { bold = true; fg = "#C586C0" ;};
		RainbowDelimiterRed = { fg = "#E06C75" ;};
		RainbowDelimiterYellow = { fg = "#E5C07B" ;};
		RainbowDelimiterBlue = { fg = "#61AFEF" ;};
		RainbowDelimiterGreen = { fg = "#98C379" ;};
		RainbowDelimiterCyan = { };
		RainbowDelimiterOrange = { fg = "#D19A66" ;};
		RainbowDelimiterViolet = { fg = "#C678DD" ;};
		LspInfoBorder = { bg = "NONE"; fg = "#5A5A5A" ;};
		WarningMsg = { bg = "#1F1F1F"; bold = true; fg = "#F44747" ;};
		SpellRare = { sp = "#646695"; undercurl = true; fg = "NONE" ;};
		SpellLocal = { sp = "#569CD6"; undercurl = true; fg = "NONE" ;};
		Whitespace = { fg = "#5A5A5A" ;};
		NormalFloat = { bg = "#272727" ;};
		WinBar = { bg = "#1F1F1F"; bold = true; fg = "#D4D4D4" ;};
		WinBarNc = { bg = "#1F1F1F"; fg = "#D4D4D4" ;};
		QuickFixLine = { bold = true ;};
		"@error" = { bg = "NONE"; fg = "#F44747" ;};
		"@punctuation.bracket" = { bg = "NONE"; fg = "#D4D4D4" ;};
		"@punctuation.special" = { bg = "NONE"; fg = "#D4D4D4" ;};
		"@punctuation.delimiter" = { bg = "NONE"; fg = "#D4D4D4" ;};
		"@comment" = { bg = "NONE"; italic = true; fg = "#6A9955" ;};
		"@comment.note" = { bg = "NONE"; bold = true; fg = "#4EC9B0" ;};
		"@comment.warning" = { bg = "NONE"; bold = true; fg = "#D7BA7D" ;};
		"@comment.error" = { bg = "NONE"; bold = true; fg = "#F44747" ;};
		"@constant" = { bg = "NONE"; fg = "#4FC1FF" ;};
		"@constant.builtin" = { bg = "NONE"; fg = "#569CD6" ;};
		"@constant.macro" = { bg = "NONE"; fg = "#4EC9B0" ;};
		"@string.regexp" = { bg = "NONE"; fg = "#CE9178" ;};
		"@string" = { bg = "NONE"; fg = "#CE9178" ;};
		"@character" = { bg = "NONE"; fg = "#CE9178" ;};
		"@number" = { bg = "NONE"; fg = "#B5CEA8" ;};
		"@number.float" = { bg = "NONE"; fg = "#B5CEA8" ;};
		"@boolean" = { bg = "NONE"; fg = "#569CD6" ;};
		"@annotation" = { bg = "NONE"; fg = "#DCDCAA" ;};
		"@attribute" = { bg = "NONE"; fg = "#DCDCAA" ;};
		"@attribute.builtin" = { bg = "NONE"; fg = "#4EC9B0" ;};
		"@module" = { bg = "NONE"; fg = "#4EC9B0" ;};
		"@function" = { bg = "NONE"; fg = "#DCDCAA" ;};
		"@function.builtin" = { bg = "NONE"; fg = "#DCDCAA" ;};
		"@function.macro" = { bg = "NONE"; fg = "#DCDCAA" ;};
		"@function.method" = { bg = "NONE"; fg = "#DCDCAA" ;};
		"@define" = { bg = "NONE"; fg = "#C586C0" ;};
		"@variable" = { bg = "NONE"; fg = "#9CDCFE" ;};
		"@variable.builtin" = { bg = "NONE"; fg = "#569CD6" ;};
		"@variable.parameter" = { bg = "NONE"; fg = "#9CDCFE" ;};
		"@variable.parameter.reference" = { bg = "NONE"; fg = "#9CDCFE" ;};
		"@variable.member" = { bg = "NONE"; fg = "#9CDCFE" ;};
		"@property" = { bg = "NONE"; fg = "#9CDCFE" ;};
		"@constructor" = { bg = "NONE"; fg = "#569CD6" ;};
		"@label" = { bg = "NONE"; fg = "#9CDCFE" ;};
		"@keyword" = { bg = "NONE"; fg = "#569CD6" ;};
		"@keyword.conditional" = { bg = "NONE"; fg = "#C586C0" ;};
		"@keyword.repeat" = { bg = "NONE"; fg = "#C586C0" ;};
		"@keyword.return" = { bg = "NONE"; fg = "#C586C0" ;};
		"@keyword.exception" = { bg = "NONE"; fg = "#C586C0" ;};
		"@keyword.import" = { bg = "NONE"; fg = "#C586C0" ;};
		"@operator" = { bg = "NONE"; fg = "#D4D4D4" ;};
		"@type" = { bg = "NONE"; fg = "#4EC9B0" ;};
		"@type.qualifier" = { bg = "NONE"; fg = "#569CD6" ;};
		"@structure" = { bg = "NONE"; fg = "#9CDCFE" ;};
		"@tag" = { bg = "NONE"; fg = "#569CD6" ;};
		"@tag.builtin" = { bg = "NONE"; fg = "#569CD6" ;};
		"@tag.delimiter" = { bg = "NONE"; fg = "#808080" ;};
		"@tag.attribute" = { bg = "NONE"; fg = "#9CDCFE" ;};
		"@text" = { bg = "NONE"; fg = "#D4D4D4" ;};
		"@markup.strong" = { bold = true; fg = "#569CD6" ;};
		"@markup.italic" = { bg = "NONE"; italic = true; fg = "#D4D4D4" ;};
		"@markup.underline" = { bg = "NONE"; underline = true; fg = "#D7BA7D" ;};
		"@markup.strikethrough" = { bg = "NONE"; strikethrough = true; fg = "#D4D4D4" ;};
		"@markup.heading" = { bold = true; fg = "#569CD6" ;};
		"@markup.raw" = { bg = "NONE"; fg = "#D4D4D4" ;};
		"@markup.raw.markdown" = { bg = "NONE"; fg = "#CE9178" ;};
		"@markup.raw.markdown_inline" = { bg = "NONE"; fg = "#CE9178" ;};
		"@markup.link.label" = { bg = "NONE"; underline = false; fg = "#9CDCFE" ;};
		"@markup.link.url" = { bg = "NONE"; underline = false; fg = "#D4D4D4" ;};
		"@markup.list.checked" = { link = "Todo" ;};
		"@markup.list.unchecked" = { link = "Todo" ;};
		"@textReference" = { fg = "#CE9178" ;};
		"@stringEscape" = { bold = true; fg = "#CE9178" ;};
		"@diff.plus" = { link = "DiffAdd" ;};
		"@diff.minus" = { link = "DiffDelete" ;};
		"@diff.delta" = { link = "DiffChange" ;};
		"@type.builtin" = { bg = "NONE"; fg = "#569CD6" ;};
		"@lsp.typemod.type.defaultLibrary" = { link = "@type.builtin" ;};
		"@lsp.type.type" = { link = "@type" ;};
		"@lsp.type.typeParameter" = { link = "@type" ;};
		"@lsp.type.macro" = { link = "@constant" ;};
		"@lsp.type.enumMember" = { link = "@constant" ;};
		"@lsp.typemod.variable.readonly" = { link = "@constant" ;};
		"@lsp.typemod.property.readonly" = { link = "@constant" ;};
		"@lsp.typemod.variable.constant" = { link = "@constant" ;};
		"@lsp.type.member" = { link = "@function" ;};
		"@lsp.type.keyword" = { link = "@keyword" ;};
		"@lsp.typemod.keyword.controlFlow" = { bg = "NONE"; fg = "#C586C0" ;};
		"@lsp.type.comment.c" = { bg = "NONE"; fg = "#51504F" ;};
		"@lsp.type.comment.cpp" = { bg = "NONE"; fg = "#51504F" ;};
		"@event" = { link = "Identifier" ;};
		"@interface" = { link = "Identifier" ;};
		"@modifier" = { link = "Identifier" ;};
		"@regexp" = { bg = "NONE"; fg = "#F44747" ;};
		"@decorator" = { link = "Identifier" ;};
		markdownBold = { bold = true; fg = "#569CD6" ;};
		markdownCode = { bg = "NONE"; fg = "#CE9178" ;};
		markdownRule = { bold = true; fg = "#569CD6" ;};
		markdownCodeDelimiter = { bg = "NONE"; fg = "#D4D4D4" ;};
		markdownHeadingDelimiter = { bg = "NONE"; fg = "#569CD6" ;};
		markdownFootnote = { bg = "NONE"; fg = "#CE9178" ;};
		markdownFootnoteDefinition = { fg = "#CE9178" ;};
		markdownUrl = { bg = "NONE"; underline = true; fg = "#D4D4D4" ;};
		markdownLinkText = { fg = "#CE9178" ;};
		markdownEscape = { fg = "#CE9178" ;};
		"@markup.environment.name.latex" = { fg = "#9CDCFE" ;};
		"@function.macro.latex" = { fg = "#C586C0" ;};
		"@operator.latex" = { fg = "#569CD6" ;};
		"@punctuation.special.latex" = { fg = "#569CD6" ;};
		"@string.latex" = { fg = "#4EC9B0" ;};
		GitSignsAdd = { fg = "#6A9955" ;};
		GitSignsChange = { fg = "#DCDCAA" ;};
		GitSignsDelete = { fg = "#F44747" ;};
		GitSignsAddLn = { bg = "#6A9955"; fg = "#1F1F1F" ;};
		GitSignsChangeLn = { bg = "#DCDCAA"; fg = "#1F1F1F" ;};
		GitSignsDeleteLn = { bg = "#F44747"; fg = "#1F1F1F" ;};
		DiagnosticOk = { bg = "NONE"; fg = "#4EC9B0" ;};
		DiagnosticError = { fg = "#F44747" ;};
		DiagnosticWarn = { fg = "#DCDCAA" ;};
		DiagnosticInfo = { fg = "#569CD6" ;};
		DiagnosticHint = { fg = "#569CD6" ;};
		DiagnosticUnderlineError = { undercurl = true; sp = "#F44747" ;};
		DiagnosticUnderlineWarn = { undercurl = true; sp = "#DCDCAA" ;};
		DiagnosticUnderlineInfo = { undercurl = true; sp = "#569CD6" ;};
		DiagnosticUnderlineHint = { undercurl = true; sp = "#569CD6" ;};
		LspReferenceText = { bg = "#343B41" ;};
		LspReferenceRead = { bg = "#343B41" ;};
		LspReferenceWrite = { bg = "#343B41" ;};
		LspInlayHint = { bg = "#353738"; fg = "#8D949D" ;};
		AerialArrayIcon = { link = "Type" ;};
		AerialBooleanIcon = { link = "Boolean" ;};
		AerialClassIcon = { link = "Include" ;};
		AerialConstantIcon = { link = "Constant" ;};
		AerialConstructorIcon = { link = "@constructor" ;};
		AerialEnumIcon = { link = "@number" ;};
		AerialEnumMemberIcon = { link = "@number" ;};
		AerialEventIcon = { link = "@constant" ;};
		AerialFieldIcon = { link = "@variable.member" ;};
		AerialFileIcon = { link = "Tag" ;};
		AerialFunctionIcon = { link = "Function" ;};
		AerialInterfaceIcon = { link = "Type" ;};
		AerialKeyIcon = { link = "Constant" ;};
		AerialMethodIcon = { link = "Function" ;};
		AerialModuleIcon = { link = "Exception" ;};
		AerialNamespaceIcon = { link = "Include" ;};
		AerialNullIcon = { link = "Constant" ;};
		AerialNumberIcon = { link = "Number" ;};
		AerialObjectIcon = { link = "Type" ;};
		AerialOperatorIcon = { link = "Operator" ;};
		AerialPackageIcon = { link = "Label" ;};
		AerialPropertyIcon = { link = "@property" ;};
		AerialStringIcon = { link = "String" ;};
		AerialStructIcon = { link = "Type" ;};
		AerialTypeParameterIcon = { link = "Type" ;};
	};

	programs.nixvim.globals = {
		terminal_color_10 = "#6A9955";
		terminal_color_3 = "#DCDCAA";
		terminal_color_11 = "#DCDCAA";
		terminal_color_4 = "#569CD6";
		terminal_color_12 = "#569CD6";
		terminal_color_5 = "#C586C0";
		terminal_color_13 = "#C586C0";
		terminal_color_6 = "#4EC9B0";
		terminal_color_14 = "#4EC9B0";
		terminal_color_0 = "#1F1F1F";
		terminal_color_8 = "#808080";
		terminal_color_7 = "#D4D4D4";
		terminal_color_15 = "#D4D4D4";
		terminal_color_1 = "#F44747";
		terminal_color_9 = "#F44747";
		terminal_color_2 = "#6A9955";
	};
}