{
  homebrew.casks = [
    "adobe-acrobat-pro"
    "adobe-creative-cloud"
    "chatwise"
    "cherry-studio"
    "claude"
    "codeedit"
    "comfyui"
    "diffusionbee"
    "github"
    "github-copilot-for-xcode"
    "lm-studio"
    "miaoyan"
    "neohtop"
    "openra"
    "orbstack"
    "sage"
    "unite"
  ];
}
