{
	programs.nixvim.highlight = {
		"@module.latex" = { fg = "#70c2be"; italic = true ;};
		"@number" = { link = "Number" ;};
		"@number.float" = { link = "Float" ;};
		"@operator" = { link = "Operator" ;};
		"@property" = { link = "@variable.member" ;};
		"@variable.member" = { fg = "#70c2be" ;};
		"@punctuation.bracket" = { link = "Delimiter" ;};
		"@punctuation.delimiter" = { link = "Delimiter" ;};
		"@punctuation.special" = { link = "Special" ;};
		"@punctuation.special.diff" = { link = "Delimiter" ;};
		"@string" = { link = "String" ;};
		"@string.documentation" = { fg = "#ABC896" ;};
		"@string.escape" = { fg = "#f08080" ;};
		"@string.regexp" = { link = "Constant" ;};
		"@string.special" = { link = "Special" ;};
		"@string.special.path" = { fg = "#96c7ef"; underline = true ;};
		"@string.special.path.diff" = { fg = "#96c7ef" ;};
		"@string.special.symbol" = { link = "@variable.member" ;};
		"@string.special.url" = { fg = "#70c2be"; underline = true; italic = true ;};
		"@tag" = { fg = "#aaaaff" ;};
		"@tag.attribute" = { link = "@variable.member" ;};
		"@tag.builtin" = { link = "@tag" ;};
		"@tag.delimiter" = { link = "Delimiter" ;};
		"@type" = { link = "Type" ;};
		"@type.builtin" = { link = "Type" ;};
		"@type.definition" = { link = "Type" ;};
		"@variable" = { fg = "#f1e9d2" ;};
		"@variable.parameter" = { fg = "#f08080"; italic = true ;};
		"@variable.parameter.builtin" = { fg = "#e75a7c"; italic = true ;};
		"@lsp.mod.readonly" = { link = "@constant" ;};
		"@lsp.mod.typeHint" = { link = "@type" ;};
		"@lsp.type.boolean" = { link = "@boolean" ;};
		"@lsp.type.builtinAttribute" = { link = "@attribute" ;};
		"@lsp.type.builtinConstant" = { link = "@constant.builtin" ;};
		"@lsp.type.builtinType" = { link = "@type.builtin" ;};
		"@lsp.type.class.markdown" = { };
		"@lsp.type.comment" = { };
		"@lsp.type.decorator" = { link = "@attribute" ;};
		"@lsp.type.derive" = { link = "@constructor" ;};
		"@lsp.type.deriveHelper" = { link = "@attribute" ;};
		"@lsp.type.enum" = { link = "@type" ;};
		"@lsp.type.enumMember" = { link = "@constant" ;};
		"@lsp.type.escapeSequence" = { link = "@string.escape" ;};
		"@lsp.type.event" = { link = "Label" ;};
		"@lsp.type.formatSpecifier" = { link = "@punctuation.special" ;};
		"@lsp.type.generic" = { };
		"@lsp.type.interface" = { link = "@type" ;};
		"@lsp.type.keyword" = { link = "@keyword" ;};
		"@lsp.type.lifetime" = { link = "StorageClass" ;};
		"@lsp.type.macro" = { link = "Macro" ;};
		"@lsp.type.magicFunction" = { link = "@function.builtin" ;};
		"@lsp.type.method" = { link = "@function.method" ;};
		"@lsp.type.namespace" = { link = "@module" ;};
		"@lsp.type.number" = { link = "@number" ;};
		"@lsp.type.operator" = { link = "@operator" ;};
		"@lsp.type.operator.cpp" = { };
		"@lsp.type.parameter" = { link = "@variable.parameter" ;};
		"@lsp.type.property" = { link = "@property" ;};
		"@lsp.type.selfKeyword" = { link = "@variable.builtin" ;};
		"@lsp.type.selfTypeKeyword" = { link = "@type" ;};
		"@lsp.type.string" = { link = "" ;};
		"@lsp.type.typeAlias" = { link = "@type.definition" ;};
		"@lsp.type.typeParameter" = { link = "@type" ;};
		"@lsp.type.unresolvedReference" = { undercurl = true; sp = "#e75a7c" ;};
		"@lsp.type.variable" = { };
		"@lsp.typemod.class.defaultLibrary" = { link = "@type.builtin" ;};
		"@lsp.typemod.enum.defaultLibrary" = { link = "@type.builtin" ;};
		"@lsp.typemod.enumMember.defaultLibrary" = { link = "@constant.builtin" ;};
		"@lsp.typemod.function.defaultLibrary" = { link = "@function.builtin" ;};
		"@lsp.typemod.function.builtin" = { link = "@function.builtin" ;};
		"@lsp.typemod.function.readonly" = { link = "@function.method" ;};
		"@lsp.typemod.generic.attribute" = { link = "@keyword" ;};
		"@lsp.typemod.keyword.async" = { link = "@keyword.coroutine" ;};
		"@lsp.typemod.keyword.injected" = { link = "@keyword" ;};
		AerialEventIcon = { fg = "#dbb651" ;};
		BlinkCmpKindField = { fg = "#70c2be"; reverse = false ;};
		AerialFieldIcon = { fg = "#70c2be" ;};
		BlinkCmpKindConstant = { fg = "#ff9966"; reverse = false ;};
		AerialConstantIcon = { fg = "#ff9966" ;};
		BlinkCmpKindFolder = { fg = "#96c7ef"; reverse = false ;};
		AerialFolderIcon = { fg = "#96c7ef" ;};
		BlinkCmpKindInterface = { fg = "#8fb573"; reverse = false ;};
		AerialInterfaceIcon = { fg = "#8fb573" ;};
		BlinkCmpKindKey = { fg = "#70c2be"; reverse = false ;};
		AerialKeyIcon = { fg = "#70c2be" ;};
		BlinkCmpKindBoolean = { fg = "#ff9966"; reverse = false ;};
		AerialBooleanIcon = { fg = "#ff9966" ;};
		BlinkCmpKindModule = { fg = "#96c7ef"; reverse = false ;};
		AerialModuleIcon = { fg = "#96c7ef" ;};
		BlinkCmpKindNamespace = { fg = "#96c7ef"; reverse = false ;};
		AerialNamespaceIcon = { fg = "#96c7ef" ;};
		BlinkCmpKindNull = { fg = "#5b5e5a"; reverse = false ;};
		AerialNullIcon = { fg = "#5b5e5a" ;};
		BlinkCmpKindObject = { fg = "#e75a7c"; reverse = false ;};
		AerialObjectIcon = { fg = "#e75a7c" ;};
		BlinkCmpKindPackage = { fg = "#dbb651"; reverse = false ;};
		AerialPackageIcon = { fg = "#dbb651" ;};
		BlinkCmpKindProperty = { fg = "#70c2be"; reverse = false ;};
		AerialPropertyIcon = { fg = "#70c2be" ;};
		BlinkCmpKindReference = { fg = "#ff9966"; reverse = false ;};
		AerialReferenceIcon = { fg = "#ff9966" ;};
		AerialSnippetIcon = { fg = "#df73ff" ;};
		BlinkCmpKindStruct = { fg = "#dbb651"; reverse = false ;};
		AerialStructIcon = { fg = "#dbb651" ;};
		BlinkCmpKindText = { fg = "#838781"; reverse = false ;};
		AerialTextIcon = { fg = "#838781" ;};
		BlinkCmpKindTypeParameter = { fg = "#f08080"; reverse = false ;};
		AerialTypeParameterIcon = { fg = "#f08080" ;};
		BlinkCmpKindUnit = { fg = "#dbb651"; reverse = false ;};
		AerialUnitIcon = { fg = "#dbb651" ;};
		BlinkCmpKindValue = { fg = "#ff9966"; reverse = false ;};
		AerialValueIcon = { fg = "#ff9966" ;};
		BlinkCmpKindVariable = { fg = "#e75a7c"; reverse = false ;};
		AerialVariableIcon = { fg = "#e75a7c" ;};
		BlinkCmpKindFunction = { fg = "#57a5e5"; reverse = false ;};
		AerialFunctionIcon = { fg = "#57a5e5" ;};
		"@lsp.typemod.macro.defaultLibrary" = { link = "@function.builtin" ;};
		"@lsp.typemod.method.defaultLibrary" = { link = "@function.builtin" ;};
		"@lsp.typemod.method.readonly" = { link = "@function.method" ;};
		"@lsp.typemod.operator.injected" = { link = "@operator" ;};
		"@lsp.typemod.parameter.mutable" = { fg = "#E28899" ;};
		"@lsp.typemod.parameter.readonly" = { fg = "#F88D73" ;};
		"@lsp.typemod.property.readonly" = { fg = "#80BC99" ;};
		"@lsp.typemod.string.injected" = { link = "@string" ;};
		"@lsp.typemod.struct.defaultLibrary" = { link = "@type.builtin" ;};
		"@lsp.typemod.type.defaultLibrary" = { link = "@type.builtin" ;};
		"@lsp.typemod.typeAlias.defaultLibrary" = { link = "@type.builtin" ;};
		"@lsp.typemod.variable.callable" = { link = "@function" ;};
		WarningMsg = { fg = "#dbb651"; bold = true ;};
		"@lsp.typemod.variable.global" = { fg = "#F098AD" ;};
		"@lsp.typemod.variable.injected" = { link = "@variable" ;};
		"@lsp.typemod.variable.mutable" = { fg = "#CCD6AE" ;};
		"@lsp.typemod.variable.static" = { fg = "#96c7ef" ;};
		TreesitterContext = { bg = "#2f312c" ;};
		DiagnosticDeprecated = { link = "Strike" ;};
		DiagnosticOk = { fg = "#8fb573" ;};
		DiagnosticUnnecessary = { link = "Comment" ;};
		DiagnosticError = { fg = "#e75a7c" ;};
		DiagnosticHint = { fg = "#aaaaff" ;};
		DiagnosticInfo = { fg = "#70c2be" ;};
		DiagnosticWarn = { fg = "#dbb651" ;};
		DiagnosticVirtualTextError = { bg = "#382B2C"; fg = "#e75a7c" ;};
		DiagnosticVirtualTextWarn = { bg = "#373428"; fg = "#dbb651" ;};
		DiagnosticVirtualTextInfo = { bg = "#2D3633"; fg = "#70c2be" ;};
		DiagnosticVirtualTextHint = { bg = "#323339"; fg = "#aaaaff" ;};
		DiagnosticUnderlineError = { undercurl = true; underline = false; sp = "#e75a7c" ;};
		DiagnosticUnderlineHint = { undercurl = true; underline = false; sp = "#aaaaff" ;};
		DiagnosticUnderlineInfo = { undercurl = true; underline = false; sp = "#57a5e5" ;};
		DiagnosticUnderlineWarn = { undercurl = true; underline = false; sp = "#dbb651" ;};
		DiagnosticUnderlineOk = { undercurl = true; underline = false; sp = "#8fb573" ;};
		LspReferenceText = { bg = "#383b35" ;};
		LspReferenceWrite = { bg = "#383b35" ;};
		LspReferenceRead = { bg = "#383b35" ;};
		LspCodeLens = { link = "Comment" ;};
		LspCodeLensSeparator = { fg = "#5b5e5a" ;};
		LspInlayHint = { fg = "#5b5e5a" ;};
		BlinkCmpGhostText = { fg = "#838781"; nocombine = true; bg = "#252623"; italic = true ;};
		BlinkCmpLabel = { fg = "#f1e9d2" ;};
		BlinkCmpLabelMatch = { fg = "#70c2be" ;};
		BlinkCmpLabelDeprecated = { fg = "#838781"; strikethrough = true ;};
		BlinkCmpKind = { fg = "#aaaaff"; reverse = false ;};
		BlinkCmpKindCopilot = { fg = "#70c2be"; reverse = false ;};
		BlinkCmpMenu = { link = "NormalFloat" ;};
		BlinkCmpMenuBorder = { link = "FloatBorder" ;};
		BlinkCmpDocBorder = { link = "FloatBorder" ;};
		DropBarMenuNormalFloat = { link = "Pmenu" ;};
		DropBarMenuCurrentContext = { fg = "#FFB38C"; bold = true ;};
		GitSignsAdd = { fg = "#8fb573" ;};
		GitSignsAddLn = { fg = "#8fb573" ;};
		GitSignsAddNr = { fg = "#8fb573" ;};
		GitSignsChange = { fg = "#57a5e5" ;};
		GitSignsChangeLn = { fg = "#57a5e5" ;};
		GitSignsChangeNr = { fg = "#57a5e5" ;};
		GitSignsDelete = { fg = "#e75a7c" ;};
		GitSignsDeleteLn = { fg = "#e75a7c" ;};
		GitSignsDeleteNr = { fg = "#e75a7c" ;};
		GitSignsUntracked = { fg = "#dbb651" ;};
		GitSignsUntrackedLn = { fg = "#dbb651" ;};
		GitSignsUntrackedNr = { fg = "#dbb651" ;};
		AerialLine = { fg = "#aaaaff"; bold = true; bg = "#383b35" ;};
		RainbowDelimiterRed = { fg = "#ED839D" ;};
		RainbowDelimiterYellow = { fg = "#E4C87D" ;};
		RainbowDelimiterBlue = { fg = "#81BCEC" ;};
		RainbowDelimiterOrange = { fg = "#FFB38C" ;};
		RainbowDelimiterGreen = { fg = "#ABC896" ;};
		RainbowDelimiterViolet = { fg = "#BFBFFF" ;};
		RainbowDelimiterCyan = { fg = "#94D1CE" ;};
		MiniHipatternsFixme = { fg = "#252623"; bold = true; bg = "#e75a7c" ;};
		MiniHipatternsHack = { fg = "#252623"; bold = true; bg = "#dbb651" ;};
		MiniHipatternsNote = { fg = "#252623"; bold = true; bg = "#70c2be" ;};
		MiniHipatternsTodo = { fg = "#252623"; bold = true; bg = "#aaaaff" ;};
		MiniIconsAzure = { fg = "#68aee8" ;};
		MiniIconsBlue = { fg = "#57a5e5" ;};
		MiniIconsCyan = { fg = "#70c2be" ;};
		MiniIconsGreen = { fg = "#8fb573" ;};
		MiniIconsGrey = { fg = "#838781" ;};
		MiniIconsOrange = { fg = "#ff9966" ;};
		MiniIconsPurple = { fg = "#aaaaff" ;};
		MiniIconsRed = { fg = "#e75a7c" ;};
		MiniIconsYellow = { fg = "#dbb651" ;};
		BlinkCmpKindOperator = { fg = "#C5C2EE"; reverse = false ;};
		AerialOperatorIcon = { fg = "#C5C2EE" ;};
		BlinkCmpKindFile = { fg = "#8fb573"; reverse = false ;};
		AerialFileIcon = { fg = "#8fb573" ;};
		BlinkCmpKindMethod = { fg = "#57a5e5"; reverse = false ;};
		BlinkCmpKindSnippet = { fg = "#df73ff"; reverse = false; italic = true ;};
		LspDiagnosticsDefaultError = { fg = "#e75a7c" ;};
		LspDiagnosticsDefaultHint = { fg = "#aaaaff" ;};
		LspDiagnosticsDefaultInformation = { fg = "#70c2be" ;};
		LspDiagnosticsDefaultWarning = { fg = "#dbb651" ;};
		LspDiagnosticsUnderlineError = { undercurl = true; underline = false; sp = "#e75a7c" ;};
		LspDiagnosticsUnderlineHint = { undercurl = true; underline = false; sp = "#aaaaff" ;};
		Normal = { fg = "#f1e9d2"; bg = "#252623" ;};
		NormalNC = { fg = "#f1e9d2"; bg = "#252623" ;};
		NormalFloat = { fg = "#f1e9d2"; bg = "#252623" ;};
		FloatBorder = { fg = "#aaaaff"; bg = "#252623" ;};
		FloatTitle = { fg = "#e75a7c" ;};
		FloatFooter = { fg = "#838781" ;};
		Terminal = { fg = "#f1e9d2"; bg = "#252623" ;};
		EndOfBuffer = { fg = "#252623" ;};
		FoldColumn = { fg = "#f1e9d2" ;};
		Folded = { fg = "#f1e9d2"; bg = "#2f312c" ;};
		SignColumn = { fg = "#f1e9d2" ;};
		ToolbarLine = { fg = "#f1e9d2" ;};
		Cursor = { reverse = true ;};
		lCursor = { link = "Cursor" ;};
		CursorIM = { link = "Cursor" ;};
		CursorColumn = { link = "CursorLine" ;};
		CursorLine = { bg = "#2f312c" ;};
		ColorColumn = { bg = "#3B4235" ;};
		CursorLineNr = { fg = "#f1e9d2" ;};
		LineNr = { fg = "#5b5e5a" ;};
		Conceal = { fg = "#838781" ;};
		LspDiagnosticsVirtualTextHint = { bg = "#323339"; fg = "#aaaaff" ;};
		LspDiagnosticsVirtualTextInformation = { bg = "#2D3633"; fg = "#70c2be" ;};
		LspDiagnosticsVirtualTextWarning = { bg = "#373428"; fg = "#dbb651" ;};
		LspDiagnosticsVirtualTextError = { bg = "#382B2C"; fg = "#e75a7c" ;};
		LspDiagnosticsUnderlineWarning = { undercurl = true; underline = false; sp = "#dbb651" ;};
		LspDiagnosticsUnderlineInformation = { undercurl = true; underline = false; sp = "#57a5e5" ;};
		AerialKeywordIcon = { fg = "#aaaaff" ;};
		BlinkCmpKindKeyword = { fg = "#aaaaff"; reverse = false ;};
		AerialStringIcon = { fg = "#8fb573" ;};
		DiffAdd = { fg = "NONE"; bg = "#40531b" ;};
		DiffChange = { fg = "NONE"; bg = "#2a3a57" ;};
		DiffDelete = { fg = "NONE"; bg = "#893f45" ;};
		DiffText = { fg = "NONE"; bg = "#3a4a67" ;};
		DiffAdded = { fg = "#8fb573" ;};
		DiffRemoved = { fg = "#e75a7c" ;};
		DiffFile = { fg = "#70c2be" ;};
		DiffIndexLine = { fg = "#5b5e5a" ;};
		Directory = { fg = "#57a5e5" ;};
		ErrorMsg = { fg = "#e75a7c"; bold = true ;};
		BlinkCmpKindString = { fg = "#8fb573"; reverse = false ;};
		MoreMsg = { fg = "#57a5e5"; bold = true ;};
		CurSearch = { fg = "#252623"; bg = "#ff9966" ;};
		IncSearch = { link = "CurSearch" ;};
		Search = { fg = "#252623"; bg = "#e2c792" ;};
		Substitute = { fg = "#252623"; bg = "#8fb573" ;};
		MatchParen = { fg = "#ff9966"; bold = true; bg = "#5b5e5a" ;};
		ModeMsg = { fg = "#94D1CE"; bold = true ;};
		NonText = { fg = "#5b5e5a" ;};
		Whitespace = { link = "NonText" ;};
		SpecialKey = { link = "NonText" ;};
		Pmenu = { fg = "#f1e9d2"; bg = "#2f312c" ;};
		PmenuSbar = { fg = "NONE"; bg = "#2f312c" ;};
		PmenuSel = { bg = "#3a3d37" ;};
		WildMenu = { fg = "#252623"; bg = "#57a5e5" ;};
		PmenuThumb = { fg = "NONE"; bg = "#5b5e5a" ;};
		Question = { fg = "#dbb651" ;};
		SpellBad = { fg = "NONE"; undercurl = true; sp = "#e75a7c" ;};
		AerialNumberIcon = { fg = "#ff9966" ;};
		SpellCap = { fg = "NONE"; undercurl = true; sp = "#dbb651" ;};
		SpellLocal = { fg = "NONE"; undercurl = true; sp = "#57a5e5" ;};
		SpellRare = { fg = "NONE"; undercurl = true; sp = "#aaaaff" ;};
		StatusLine = { fg = "#f1e9d2"; bg = "#383b35" ;};
		StatusLineNC = { fg = "#5b5e5a"; bg = "#2f312c" ;};
		TabLine = { fg = "#f1e9d2"; bg = "#2f312c" ;};
		TabLineFill = { fg = "#5b5e5a"; bg = "#2f312c" ;};
		TabLineSel = { fg = "#252623"; bg = "#f1e9d2" ;};
		VertSplit = { fg = "#3a3d37" ;};
		Title = { fg = "#70c2be"; bold = true ;};
		Visual = { bg = "#3a3d37" ;};
		VisualNOS = { fg = "NONE"; bg = "#383b35"; underline = true ;};
		BlinkCmpKindNumber = { fg = "#ff9966"; reverse = false ;};
		WinSeparator = { fg = "#3a3d37" ;};
		WinBar = { fg = "#838781" ;};
		WinBarNC = { link = "WinBar" ;};
		QuickFixLine = { fg = "#57a5e5"; underline = true ;};
		Debug = { fg = "#ff9966" ;};
		debugPC = { bg = "#1c1e1b" ;};
		debugBreakpoint = { fg = "#252623"; bg = "#e75a7c" ;};
		ToolbarButton = { fg = "#252623"; bg = "#68aee8" ;};
		String = { fg = "#8fb573" ;};
		Constant = { fg = "#ff9966" ;};
		Character = { link = "Constant" ;};
		Number = { link = "Constant" ;};
		Float = { link = "Constant" ;};
		Boolean = { link = "Constant" ;};
		Type = { fg = "#dbb651" ;};
		Typedef = { link = "Type" ;};
		Structure = { link = "Type" ;};
		StorageClass = { fg = "#dbb651"; italic = true ;};
		Identifier = { fg = "#e75a7c" ;};
		PreProc = { fg = "#aaaaff" ;};
		PreCondit = { link = "PreProc" ;};
		Include = { link = "PreProc" ;};
		Define = { link = "PreProc" ;};
		Keyword = { fg = "#aaaaff" ;};
		Exception = { link = "Keyword" ;};
		Conditional = { fg = "#aaaaff"; italic = true ;};
		Repeat = { link = "Keyword" ;};
		Statement = { fg = "#aaaaff" ;};
		Macro = { fg = "#df73ff" ;};
		Error = { fg = "#e75a7c" ;};
		Label = { fg = "#e75a7c"; bold = true ;};
		Special = { fg = "#e75a7c" ;};
		SpecialChar = { link = "Special" ;};
		Function = { fg = "#57a5e5" ;};
		Operator = { fg = "#C5C2EE" ;};
		Tag = { fg = "#57a5e5" ;};
		Delimiter = { fg = "#838781" ;};
		Comment = { fg = "#838781"; italic = true ;};
		SpecialComment = { link = "Comment" ;};
		Todo = { fg = "#111210"; bold = true; bg = "#aaaaff" ;};
		Underlined = { underline = true ;};
		Bold = { bold = true ;};
		Italic = { italic = true ;};
		Strike = { strikethrough = true ;};
		AerialMethodIcon = { fg = "#57a5e5" ;};
		"@attribute" = { fg = "#70c2be" ;};
		"@attribute.typescript" = { fg = "#57a5e5" ;};
		"@boolean" = { link = "Boolean" ;};
		"@character" = { link = "Character" ;};
		"@character.special" = { link = "Special" ;};
		"@comment" = { fg = "#e2c792"; italic = true ;};
		"@comment.error" = { fg = "#111210"; bold = true; bg = "#e75a7c" ;};
		"@comment.note" = { fg = "#111210"; bold = true; bg = "#57a5e5" ;};
		"@comment.todo" = { link = "Todo" ;};
		"@comment.warning" = { fg = "#111210"; bold = true; bg = "#ff9966" ;};
		"@comment.warning.gitcommit" = { bg = "#5C4334" ;};
		"@constant" = { link = "Constant" ;};
		"@constant.builtin" = { link = "Constant" ;};
		"@constant.macro" = { link = "Macro" ;};
		"@constructor" = { fg = "#dbb651"; bold = true ;};
		"@constructor.lua" = { fg = "#dbb651" ;};
		"@diff.delta" = { link = "DiffChange" ;};
		"@diff.minus" = { link = "DiffDelete" ;};
		"@diff.plus" = { link = "DiffAdd" ;};
		"@error" = { link = "Error" ;};
		"@function" = { link = "Function" ;};
		"@function.builtin" = { fg = "#ff9966" ;};
		"@function.call" = { link = "Function" ;};
		"@function.macro" = { fg = "#df73ff" ;};
		"@function.method" = { link = "Function" ;};
		"@function.method.call" = { link = "Function" ;};
		"@keyword" = { link = "Keyword" ;};
		"@keyword.conditional" = { link = "Conditional" ;};
		"@keyword.conditional.ternary" = { link = "Operator" ;};
		"@keyword.coroutine" = { link = "Keyword" ;};
		"@keyword.debug" = { link = "Keyword" ;};
		"@keyword.directive" = { link = "PreProc" ;};
		"@keyword.directive.define" = { fg = "#aaaaff"; bold = true ;};
		"@keyword.exception" = { link = "Exception" ;};
		"@keyword.import" = { link = "Include" ;};
		"@keyword.modifier" = { fg = "#aaaaff"; italic = true ;};
		"@keyword.operator" = { link = "Keyword" ;};
		"@keyword.repeat" = { link = "Repeat" ;};
		"@keyword.return" = { link = "Keyword" ;};
		"@keyword.type" = { link = "Keyword" ;};
		"@label" = { link = "Label" ;};
		"@label.diff" = { fg = "#dbb651" ;};
		"@markup.heading" = { link = "htmlTitle" ;};
		BlinkCmpKindEvent = { fg = "#dbb651"; reverse = false ;};
		"@markup.heading.1" = { link = "markdownH1" ;};
		AerialEnumMemberIcon = { fg = "#ff9966" ;};
		"@markup.heading.2" = { link = "markdownH2" ;};
		BlinkCmpKindEnumMember = { fg = "#ff9966"; reverse = false ;};
		"@markup.heading.3" = { link = "markdownH3" ;};
		AerialEnumIcon = { fg = "#dbb651" ;};
		"@markup.heading.4" = { link = "markdownH4" ;};
		BlinkCmpKindEnum = { fg = "#dbb651"; reverse = false ;};
		"@markup.heading.5" = { link = "markdownH5" ;};
		AerialConstructorIcon = { fg = "#57a5e5" ;};
		"@markup.heading.6" = { link = "markdownH6" ;};
		BlinkCmpKindConstructor = { fg = "#57a5e5"; reverse = false ;};
		"@markup.italic" = { link = "markdownItalic" ;};
		AerialColorIcon = { fg = "#8fb573" ;};
		"@markup.link" = { link = "Tag" ;};
		"@markup.link.label" = { link = "markdownLinkText" ;};
		BlinkCmpKindColor = { fg = "#8fb573"; reverse = false ;};
		"@markup.link.url" = { link = "markdownUrl" ;};
		AerialClassIcon = { fg = "#dbb651" ;};
		"@markup.list" = { link = "markdownListMarker" ;};
		BlinkCmpKindClass = { fg = "#dbb651"; reverse = false ;};
		"@markup.list.checked" = { fg = "#dbb651"; bold = true ;};
		"@markup.list.unchecked" = { fg = "#838781"; bold = true ;};
		"@markup.math" = { fg = "#96c7ef" ;};
		"@markup.quote" = { fg = "#838781" ;};
		"@markup.raw" = { link = "markdownCode" ;};
		AerialArrayIcon = { fg = "#dbb651" ;};
		"@markup.raw.block" = { link = "markdownCodeBlock" ;};
		BlinkCmpKindArray = { fg = "#dbb651"; reverse = false ;};
		"@markup.strikethrough" = { link = "markdownStrike" ;};
		AerialDefaultIcon = { fg = "#aaaaff" ;};
		"@markup.strong" = { link = "markdownBold" ;};
		BlinkCmpKindDefault = { fg = "#aaaaff"; reverse = false ;};
		"@markup.underline" = { link = "htmlUnderline" ;};
		"@lsp.typemod.variable.defaultLibrary" = { link = "@variable.builtin" ;};
		"@module" = { fg = "#96c7ef"; italic = true ;};
		"@module.builtin" = { link = "@variable.builtin" ;};
		"@variable.builtin" = { fg = "#e75a7c" ;};
	};

	programs.nixvim.globals = {
		terminal_color_1 = "#e75a7c";
		terminal_color_2 = "#8fb573";
		terminal_color_3 = "#dbb651";
		terminal_color_4 = "#57a5e5";
		terminal_color_5 = "#aaaaff";
		terminal_color_6 = "#70c2be";
		terminal_color_7 = "#f1e9d2";
		terminal_color_8 = "#5b5e5a";
		terminal_color_9 = "#e75a7c";
		terminal_color_10 = "#8fb573";
		terminal_color_11 = "#dbb651";
		terminal_color_12 = "#57a5e5";
		terminal_color_13 = "#aaaaff";
		terminal_color_14 = "#70c2be";
		terminal_color_15 = "#f1e9d2";
		terminal_color_0 = "#111210";
	};
}